### ISSUE TITLE
Windows 10 Support

### ISSUE THREAD

**Issue by OriginalFool** [xenolightning/AudioSwitcher_v1#1022]
Had previously used AudioSwitcher on Windows 10, however I've noticed from build 10122 - 10130 it has stopped functioning. 

Specifically when running, it keeps refreshing the available playback devices, making me unable to interact with the program at all. 
High CPU usage (10%) and a steady increase in memory as well.

**Comment by xenolightning** [comment]
There seems to be issues with high system resource usage in 10130. Scott Hanselman recently talked about it in his upgrade tour.

https://www.youtube.com/watch?v=PoW0MpJWMBg

I've just upgraded today, so I'll have a look into it. But it may be something broken within 10130.

**Comment by xenolightning** [comment]
Just tried it on 10130, didn't notice any issues.

Had default (no) settings checked. It may be a Windows startup issue? 

Pretty confident that it's an issue introduced with 10130.
