### ISSUE TITLE
Playback device disappears after Windows Sleeps and Wakes up.

### ISSUE THREAD

**Issue by elysoto** [xenolightning/AudioSwitcher_v1#1024]
Windows 7 Ultimate.
I have a motherboard with a Realtek audio chipset and I also have a USB Logitech G930 Headset.

When my PC Sleeps and then wakes up, the Logitech G930 is gone from the playback device selection.
It appears in the Windows Control Panel Sound Selector under playback. When I set the headset as my default device it appears in AudioSwitcher's list again and I am able to use it normally.

This is a new issue that appeared in one of the recent past releases as it worked fine for a very long time.

**Comment by xenolightning** [comment]
What version are you currently using?

**Comment by elysoto** [comment]
1.6.5.0

**Comment by elysoto** [comment]
I think there is some USB sleep mode that is confusing AudioSwitcher.
After the computer wakes, if I turn on the headset before using audioswitcher, then 'sometimes?' audioswitcher recognizes it again.

The settings "Show Disconnected/Disabled devices" don't change this.

**Comment by xenolightning** [comment]
You can try 1.6.4.0, after-which there was a change made in the way devices were added. 

Windows likes to enable devices in invalid states for 'loading' which was crashing Audio Switcher prior to 1.6.5.0.

A change has been made to resolve the crash, but it doesn't take into account Windows' silly issues.

Effectively what is happening is you are connecting a device, Audio Switcher is ignoring the 'Add Device' because it's invalid, then Windows never tells Audio Switcher it's valid.

1.6.5.1 should resolve this.

**Comment by elysoto** [comment]
I tried 1.6.4.2 and it worked immediately even during the error condition.

**Comment by elysoto** [comment]
Ok so I was wrong. 1.6.4.2 doesn't work and the same thing happens after sleep. I'm going to keep going back versions.

**Comment by elysoto** [comment]
1.6.4 works. http://services.audioswit.ch/versions/1.6.4.0/
You were right the first time. I tested it by going to sleep and waking the computer and verifying the headset was present.

So what happened is that 1.6.5 was having the issue and then I killed it and ran 1.6.4.2 and everything worked. I assumed that meant it fixed it. I guess it really just reacquired the list from Windows since it was starting up from scratch.

**Comment by xenolightning** [comment]
Yeah, I have identified the change I made that introduced this bug.

1.6.5.1 should be released in the next 24 hours. If you want to give a release client build a test to ensure it's fixed before a full release let me know, and I'll upload it to Github.

Thanks.

**Comment by elysoto** [comment]
Sure i can give it a go.

**Comment by xenolightning** [comment]
RC1 release available here:

https://github.com/xenolightning/AudioSwitcher_v1/releases/tag/1.6.5.1-RC1

**Comment by elysoto** [comment]
Yes the fix worked.

**Comment by xenolightning** [comment]
Great! Thanks for testing that. 

The final release will be out in a few hours.
