### ISSUE TITLE
StartUp needs to be delayed.

### ISSUE THREAD

**Issue by TechRoot** [xenolightning/AudioSwitcher_v1#1047]
Hello there.

Awesome work first of all!

I have a logitech wireless headset, this takes a while to become available on a brand new PC, i have noticed the default option for "Start with windows" causes issues because the program trying to retrieve a device that its not currently loaded. I maganed to solve this vía the Task Sheduler, delaying the program a few minutes, so it will start when everything is ready.

Not using this method will cause to an anormal function, including crashes/ not starting program/ program not recognizing the headset.

Maybe a native option to delay this, and wait to all the other processes to be launched before starting audioswither will make the trick.

Thanks.

**Comment by xenolightning** [comment]
Same bug as #930 #950 #1024
