### ISSUE TITLE
Feedback: Few minor problems and requests

### ISSUE THREAD

**Issue by Timmyfox** [xenolightning/AudioSwitcher_v1#106]
First off, sorry if this isn't the right place! I was trying to find a support email or something but this seemed like the best place to post some feedback other than the review section on sourceforge.

Alright, so I've only played around with the latest version (1.6.2.0) for about an hour or so as I just discovered this extremely handy app and found a few things that I missed as well as two potential bugs!

Requests:
- Customizable tray icon

Basically, I'd like to see a feature where the tray icon could be changed depending on which audio device is selected as default.

I'm thinking perhaps allow custom colors to be defined for an audio device, for example headphones could be set to "Red" and speakers could be "Blue" which would give a quick visual indicator of which device is currently selected.

Alternatively, instead of colors, there could otherwise be a predefined set of small icons to represent a various audio devices, such as speakers, headphones, maybe a DAC etc. to choose from.

- Quick switch hotkey

Rather self-explanatory. I like having hotkeys to switch between audio devices but I think it would be even better to have the option to, like the already existing "quick switch mode", use a hotkey to cycle between my frequently used devices instead of having to have one hotkey for each device.

---
Bugs/issues:
- Hotkeys doesn't work for me

Speaking of hotkeys, I can't seem to get them to work. I've tried several different configurations and I also tried 1.6.1.9 (as I had the crash-on-start issue with 1.6.1.8) and it didn't work with that one either. I've tried experimenting with a several settings but nothing seems to make hotkeys work for me unfortunately.

- Device icon not showing properly

One of my audio devices, a DAC which is connected through USB, seems to be missing its icon in the Audio Switcher interface. This also means that the little star icon doesn't show despite having set it as a "favorite device". When I set it to default device, the little checkmark icons doesn't show either.

![iconmissing](https://cloud.githubusercontent.com/assets/1836111/5222845/9fa53e28-76a7-11e4-8320-7c579970b854.jpg)

**Comment by xenolightning** [comment]
Closing, as the hotkey issue is now resolved.
