### ISSUE TITLE
No switch happens?

### ISSUE THREAD

**Issue by skallsen** [xenolightning/AudioSwitcher_v1#1138]
I have the program installed and it recognizes my soundbar speakers as well as my headphones.  No matter what I do it won't go to the speakers, only the headphones.

**Comment by skallsen** [comment]
Oh, I have windows 8 and a Dell soundbar.  The headphones are Logitech G430

**Comment by skallsen** [comment]
I restarted and the audio started from my soundbar but now I can't switch to headphones.

**Comment by xenolightning** [comment]
If you try to switch using Control Panel does it work?

**Comment by skallsen** [comment]
No, it doesn't.

**Comment by xenolightning** [comment]
If it doesn't change in Control Panel, then Audio Switcher won't be able to change it either.

There is some system limitation on your PC preventing you from changing the default device. 

Not an Audio Switcher issue, so closing.
