### ISSUE TITLE
Switching from PC to HDMI TV audio error (Windows 10)

### ISSUE THREAD

**Issue by verimeloni** [xenolightning/AudioSwitcher_v1#1278]
I have my pc hooked up to 2 monitors through DVI and to speakers via 3,5mm jack. I also have my pc hooked to my TV via HDMI which I sometimes use for watching videos etc. I've been using Audio Switcher to switch between my speakers and my TV for couple of weeks now and most of the time it works. I'm using the new Windows 10 and I have updated my audio drivers.
However, sometimes (mostly when my pc has been on for some time and I turn my TV on) when I want to switch between audio output devices, sound will come through the speakers but not from my TV. Instead, there's a brief moment of silence and if it's a Youtube video I'm watching, the video playback will stop and the video will start buffering. If I don't touch anything my pc will automatically switch the output device back to my speakers (after maybe 15 seconds), and the audio which was supposed to play during that silent period will catch up with the video. To this point I've been fixing this issue by rebooting my pc, afterwards everything works as expected.

**Comment by xenolightning** [comment]
Hmm interesting.

It sounds like it might be something outside of Audio Switchers control. 

Try switching the playback device using Control Panel. Control Panel > Sound > Playback (the old long way) and see if it still happens, if it does there's then I won't be able to fix Audio Switcher and it's a Windows 10 related issue.

out of interest what browser are you using? And is it using Adobe Flash? I know there's some weird issues with Flash and Audio Devices.

**Comment by verimeloni** [comment]
I'm using Chrome but the silent period happens when watching video files too, so I don't think the problem concerns the browser or flash. I'll try the control panel  route the next time it happens.

**Comment by xenolightning** [comment]
Ok, so won't be anything related to flash.

I'll test my laptop and see if it replicates the issue, and post my findings.

**Comment by verimeloni** [comment]
Hello, it happened again. I tried to switch the output device from Windows settings but it didn't work and I got a message saying that some audio device wasn't working properly and the system asked if I'd like to stop using that device. This has led me to believe that this is an Windows 10 driver issue. I'll take a screencapture of the message when it happens again.

**Comment by xenolightning** [comment]
Yeah certainly sounds like a driver issue.

It might be worth not running Audio Switcher, and just switching it manually, and see if it happens. Will determine if Audio Switcher is causing it. It's unlikely but may help determine the cause.
