### ISSUE TITLE
Switch Audio and Mic Hot Key

### ISSUE THREAD

**Issue by Luzr** [xenolightning/AudioSwitcher_v1#1280]
In your older version you have a way to switch the audio and the mic with a respective hot key. In the new version I only see a way to set a hot key per device.

**Comment by xenolightning** [comment]
What old version does this for you?

As far as I'm aware all version of Audio Switcher have never been able to switch multiple devices per hotkey.

**Comment by Luzr** [comment]
It must of been a different application. Are you able to make an option to use a hotkey to switch between Playback and Recording?

**Comment by xenolightning** [comment]
This will be possible in v2.0 and above.
