### ISSUE TITLE
"Startup Device" function ignores the "Enable dual switch mode"

### ISSUE THREAD

**Issue by thunderschnozzle** [xenolightning/AudioSwitcher_v1#1293]
Audio Switcher version: 1.6.6.85
Audio setup: 1) LG 29UM67-P Monitor speakers connected to NVidia GTX 690 with a DisplayPort 1.2
                     2) Roccat Kave 5.1 headphones connected to an on-board Realtek® ALC898 audio chip
OS: Windows 10 RTM BUILD 10240

Issue:

Under the "Playback" tab, I set up my headphones as both "Default Device" and "Default Communications Device" and my monitor speakers as "Startup Device". Under the "Settings" tab, I checked all the boxes except for "Disable hot keys", "Show Disabled Devices" and "Show Disconnected Devices". Then I restarted my computer.
When I signed-in to windows, my monitor speakers were set to "Default Devices", but my headphones were still set as "Default Communications Device".
It seems, as the title suggests, that the "Startup Device" function ignores the "Enable dual switch mode" option under the "Settings" tab. Can you please see if you can replicate this issue and solve it?

Other than that and the "Option for hot-key to cycle though Favorite devices" issue raised by dartharnold, I think you did a phenomenal job with this awesome and very convenient little program. Microsoft should seriously consider paying you royalties and incorporate this into windows 10.

Thanks mate!!!

**Comment by xenolightning** [comment]
Yeah I think I noticed this too, didn't really bother me as I don't use comm's for anything.

Will fix it though, and Audio Switcher will set default & comm when it's the startup device.

If only! Wouldn't mind if Microsoft just included it in their standard sound options.

**Comment by thunderschnozzle** [comment]
cool, thanks.

Yeah, I wouldn't mind that too :)
