### ISSUE TITLE
Forgetting Favourited Devices

### ISSUE THREAD

**Issue by dk0r** [xenolightning/AudioSwitcher_v1#1300]
Problem: Upon rebooting, AudioSwitcher 1.6.6.85 forgets one of favourited devices.

How to reproduce: Configure AudioSwitcher with two favourite devices (device-A and device-B). After a reboot, device-B is no longer marked with a star but device-A is still marked with a star. Now make device-B a favourite device and the star will reappear over device-B. After rebooting, device-A is still favourited/starred but device-B's star is missing and is no longer considered a favourite device.

**Comment by xenolightning** [comment]
What kind of device is B? Does it still happen if you just favourite Device B?

Sounds like Device B is USB, and Windows is disconnecting and reconnecting the device on reboots. If this happens the device is given a new Id every time, so the old favourite won't apply anymore.

You can paste the .json file in here (it's plain text) and we can see what the settings are doing.
