### ISSUE TITLE
Use Local Appdata for Settings & AutoUpdate

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#1308]
https://msdn.microsoft.com/en-us/library/system.environment.specialfolder%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

**Comment by karasuhebi** [comment]
Will there be an option to keep using the local .json file? Maybe some sort of portable mode? That'd be great. :)

**Comment by xenolightning** [comment]
@karasuhebi Unlikely. I don't think too many users care to look at the .json currently.

The AppData directory is the preferred place to store application related files. The application will still remain 100% portable, just changes the directory of settings.

I will consider adding and "Open Location" button which will take the user directly to the json file.

**Comment by karasuhebi** [comment]
I wasn't implying I wanted to look at the .json file, I was just asking if there was going to be a portable mode option that I could click or something that would make it so the .json file would be stored along with the application itself so it's easy to move from place to place. An "Open Location" button isn't necessary I don't think. I agree with you that most people won't care to look at the .json file.

**Comment by xenolightning** [comment]
Under what scenarios would you be wanting to move the json file?

The .json contains information specific to the current PC/User. These identifiers are likely to cause undefined behaviour when moved to a new PC, especially when using hotkeys.

I don't really see an issue with requiring the user to reselect options when the application is run under a new environment.

The open location, would be only for those who want to move/make a copy of the json file.

**Comment by karasuhebi** [comment]
Oh I didn't realize there was that kind of specific information in the .json file to where it would potentially cause issues to move it around between systems. Never mind then. I just thought it would have been nice to have a portable mode.

**Comment by xenolightning** [comment]
Yeah each and every sound device gets a unique identifier, and that identifier is used for hotkeys, favourites, startup etc...

Best that they don't wander from PC to PC unless the user intentionally wants to.

**Comment by karasuhebi** [comment]
>unless the user intentionally wants to.

Well that's a valid reason to have "portable mode" as an option then haha ;)
