### ISSUE TITLE
Automatic 'check for updates' function uncheck itself

### ISSUE THREAD

**Issue by thunderschnozzle** [xenolightning/AudioSwitcher_v1#1323]
Version: 1.6.6.85
OS: Windows 10 Pro (x64)

Issue: 

If you check the "Tell me when there's an update" box under the "Settings" tab and restart your PC, that option will uncheck itself when you log in to windows.

**Comment by xenolightning** [comment]
Confirmed. 

It's not saving the setting, when checked.
