### ISSUE TITLE
programm forgets devices after disconnect

### ISSUE THREAD

**Issue by TimetravelerDD** [xenolightning/AudioSwitcher_v1#1357]
when a device is temporary not available (say a unplugged USB Headset for example) the program sometimes "forgets" that device. What I mean with this that for example the "favorit" status is forgotten and when the device is reconnected it is not longer in the favorite device list and thus is it not possible to select it with a left or right click on the tray icon.

**Comment by xenolightning** [comment]
This is an issue with Windows.

It can't tell if the USB is a new device or the same device when it's plugged back in. So it just treats it as a new device everytime.

**Comment by TimetravelerDD** [comment]
Dear xenolightning,
First of all thank your for your application. I respect that you are the dev and it is ultimately your decistion. However since you are on github I hope I may illustrate another aspect before you finally decide:

This problem completely brakes the usability for me and potentially for many users. Because my USB bluetooth and HDMI Sound devices are frequently disconnected I always have to open the Preferences to switch to my other devices which makes the programm kind of obsolete.

I would like to propose the following solution:

- As I guess you can not read a device ID or something similar from the windows API so you can't identify for sure a certain device? However I think a 95% probability would be sufficient. Maybe you could read just the device name and try to indentify favorite devices by name? If somebody would argue, that there could be two devices with the same name (really?) I would say in this rare case you could still change the name in the windows settings once and be good forever (windows seems to remember/recognise the devices correctly) If this fails you could also try to read the icon id in combination with the name?

- If you really don't like the idea – please consider the following option as a workaround or additional feature:
please make an option to "show all available sound devices at right click on tray" (not only favorites)
That would already help a lot since I could choose all devices with only two clicks.
heck I would even make it other way around and name it "show only favorite devices in tray" and have it switched on by default if you prefer

To further improve on this idea  you could also make an option to "hide" certain sound devices in that list (simiar to the favorite status but other way around)

I hope I could contribute a bit to your project. In any case: thank you for your effort and your hard work!

**Comment by xenolightning** [comment]
I've looked at another way to identify devices in the past, but it's all ultimately led back to using the Id. There's no full proof way of distinguishing between different devices apart from the Id string.

It is REALLY stupid, and don't get me wrong I don't like the way Windows does it either. There may be a way to get the device serial number for some devices, but if others don't have a serial number then it's not a reliable way either.

In short there's no 100% fool-proof way of doing this.

The option of hiding some devices is a much more reasonable solution, and the behaviour is somewhat predictable. Although it suffers from the same issue reversed. If you reconnect a "hidden" device it will appear again.

You can un-favourite devices, and all devices will show in the right click menu. Not ideal but is probably more useful than opening the application for every "new device".

**Comment by TimetravelerDD** [comment]
Hi there!
thanks for the quick reply. I have no idea how many devices have this serial number but I suppose even if it works only in some cases it would help. But to be honest I can't really judge this with my limited programming knowledge. I trust you you thought about this a lot.

I'm glad that you liked the idea with hiding and I see the same problem as you mentioned – However probably still worth the effort.

In any case I can't reproduce the feature that you are describing: Are you talking about version 2 now?
If I unfav all devices I have no devices left in the tray menu.

![prtscr capture_6](https://cloud.githubusercontent.com/assets/14355674/10335854/643039da-6cf4-11e5-9123-d7c93a0f04a6.png)

**Comment by xenolightning** [comment]
It's likely that the "old" devices you favourited, are still in the settings.

These are the ones that have been connected, marked as favourite, then disconnected.

They still remain favourited by the application, even through they will never exist again.

Open up the .json settings file and clear the line "FavouriteDevices".

You can delete the entire line of make the value empty:

    "FavouriteDevices" : "",

**Comment by TimetravelerDD** [comment]
Thanks alot! That worked for me!
To make the user experience more consistent you may consider to introduce the "show only favorite devices in tray" option.

That would also alow to cycle through favorites with left click but see all devices with right click.

However for me the biggest pain-point is solved now – So I want to thank you for your effort so far! =)

**Comment by xenolightning** [comment]
Glad it's working for you.

I'm hesitant to introduce more new features into an obsolete version of the application. Supporting the old version is already taking up time which could be used for developing v2.

I'll look at the feasibility of it for v2

**Comment by TimetravelerDD** [comment]
allright, then I wish you much success with the v2!
I hope I could help a bit.
Kind regards!
