### ISSUE TITLE
Crash when connecting or disconnecting second USB Interface

### ISSUE THREAD

**Issue by joersch-sb** [xenolightning/AudioSwitcher_v1#1445]
Hi:-)

During running audioswitch, I connected a second (USB) Audio-Interface. After that is is impossible to access audioswitch per Tray Icon. I had to close the app in the task-Manager. After restarteing, all is fine. Same behaviour, when I dieconnect the USB Interface when Audioswitch is running. I Use Windows 10, a PC with onboard Audio und a MOTU Ultralite USB Interface. I really like Audioswitch. Thanks for such a usefull App!

**Comment by xenolightning** [comment]
I'll confirm this as a bug. When I'm back in the office I'll take a look at it, and se if I can reproduce it.

I should be able to test it with 2 USB devices, with on board sound.

**Comment by xenolightning** [comment]
Can't reproduce. Might be improved with the latest versions.
