### ISSUE TITLE
Windows Start

### ISSUE THREAD

**Issue by crz4all** [xenolightning/AudioSwitcher_v1#1446]
I have a problem with Audio Switch not starting up with Windows. I tried use the option in settings and manually create a shortcut in Startup folder, and nothing happen, I always need to start manually... Do you know what can be the cause? I'm using Windows 10.

**Comment by xtopolis** [comment]
I had a few issues after switching to windows 10 as well. This is how I solved mine:

I created a folder "AudioSwitcher" with the .exe and settings inside, and moved that folder to: `%userprofile%/AppData/Roaming`

I right clicked AudioSwitcher.exe and chose Create Shortcut. I moved that shortcut to: `%userprofile%/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup`

After that, I rebooted and it started up like normal.

**Comment by xenolightning** [comment]
The steps above are great. It should remove any sort of permissions issue on startup.

It's hard to say what would be causing it otherwise.

The next release should get around this issue, and always put settings in the User Data folder.
