### ISSUE TITLE
Could you support Web Cams?

### ISSUE THREAD

**Issue by DarwinJS** [xenolightning/AudioSwitcher_v1#1457]
I have one integrated on my laptops and an external one and managing them is as much of a pain as audio devices :)

**Comment by xenolightning** [comment]
In what respect?

How do you currently use multiple webcams, and what do you want to achieve?

It's highly unlikely that audioswitcher will support webcams in it's current state

**Comment by DarwinJS** [comment]
Especially "startup device" - oh but wait -windows does not support marking
them as default does it?  More important it would be cool to switch both
mic and speakers to pairings I specify.

You know what would be super helpful!

When a communication app "rings" switch to my headphones, when there is
nothing on the mic for x minutes switch back to another source I specify (
speakers.  I constantly have to do this but don't want to leave the
headphones on to hear IM tones.
D.

**Comment by xenolightning** [comment]
Yeah, no idea if it's possible for Webcams; probably not. It's application specific.

The other idea would require an insane amount of planning and testing. Something that is unlikely to happen for free; or in Audio Switcher.

Closing as issue no longer related to Audio Switcher.
