### ISSUE TITLE
Api Versioning/Packaging Issues

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#1489]
### Details:
Audio Switcher
Version: 1.6.6.85
Operating System: Microsoft Windows NT 6.2.9200.0 64-bit
Administrator Privileges: False

### User Comments:
it's crashing since a power failure. Reboot but still crashing since then.
### Stacktrace:
```
System.IO.FileNotFoundException: No se puede cargar el archivo o ensamblado 'AudioSwitcher.AudioApi.CoreAudio, Version=1.7.0.173, Culture=neutral, PublicKeyToken=fda5729e2db3a64f' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.
Nombre de archivo: 'AudioSwitcher.AudioApi.CoreAudio, Version=1.7.0.173, Culture=neutral, PublicKeyToken=fda5729e2db3a64f'
   en FortyOne.AudioSwitcher.AudioDeviceManager.get_Controller()
   en FortyOne.AudioSwitcher.AudioSwitcher..ctor()
   en FortyOne.AudioSwitcher.AudioSwitcher.get_Instance()
   en FortyOne.AudioSwitcher.Program.Main()

AVS: El registro del enlace de ensamblado está desactivado.
Para habilitar el registro de errores del enlace de ensamblado, establezca el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.
Nota: existe una disminución del rendimiento asociada registro de errores del enlace de ensamblado.
Para desactivar esta característica, elimine el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog].

```

**Comment by spectante** [comment]
I'm the one who reported the error. It happens every time the program is launched. I've been testing older versions and It seems to work fine again with version 1.6.5.1.

**Comment by xenolightning** [comment]
Yeah I'm not sure what's causing this issue.

It may have been a packaging issue, but it seems to only affect some users. 

Hoping to get another release out in the next few weeks. Should hopefully resolve the versioning/packaging issues. 

Will keep this open, and we'll keep an eye on it.

If you'd like to test an early build, to ensure it works, let me know and I'll put a beta release up.
