### ISSUE TITLE
Hotkeys don't seem to work on W10

### ISSUE THREAD

**Issue by remcoboerma** [xenolightning/AudioSwitcher_v1#1526]
1. Using version 1.6.6.85 on windows 10 (build 10586.14)
1. Rightclick on a device in AudioSwitcher playback panel
1. Select "Set Hot Key"
1. Press Alt-VolumeDown / Alt-Ctrl-Shift-F11 / ... F12  (no conflicts mentioned)
1. Repeat above three steps for another device, using another hotkey 
1. Pressing the hotkeys in windows 8.1 resulted in instant changing. In windows 10 i get no change of a device whatsoever.

**Comment by xenolightning** [comment]
I know Win10 did a large update, which may have broken a bunch of things.

It seems very strange that the hotkeys aren't responding.

Does the application switch defaults normally? Either through the UI, or the Tray Icon?

There's a new version of 1.x due out *very* soon, if possible I'd like to include a fix for this, in the new version.

**Comment by remcoboerma** [comment]
The switching works. AFAICT also the startup device works. It seems to be just the keyboard hook that isn't working. Can run/test/log something to aid with this issue?

**Comment by xenolightning** [comment]
Ok great, at least the switching still works.

I'll give it a test on my Win10 machine over the weekend, if I can't reproduce it I'll create a debug build that has a bit more logging around the issue.

Just for the record, the hotkeys aren't a keyboard hook. Keyboard hooks are bad, and can easily turn into keyloggers :) Currently it registers hotkeys with the OS

**Comment by xenolightning** [comment]
Tested on 10586.17, and hotkeys are working fine for me. Try removing the json file and recreating the hotkeys from scratch.

**Comment by remcoboerma** [comment]
Thanks, that was it. I compared the json files and they are hardly different. Any idea why recreating it helps? 

Thanks, with registering the key at the OS i meant a hook :) But i'm not into active development in fat UI's anymore. 

Thanks for the solution !

**Comment by xenolightning** [comment]
Sometimes hotkeys get into a strange state, where they think they are registered but aren't actually. So the hotkeys sit in a state of "existence", but don't function.

There is certainly a way to fix it, would require re-writing the hotkey piece, there's an open bug for exactly this: #1253
