### ISSUE TITLE
Support for Logitech and G-keys

### ISSUE THREAD

**Issue by Znubbis** [xenolightning/AudioSwitcher_v1#1542]
May I suggest support for logitech's G-keys directly? I know mumble have it so I guess they have some kind of SDK to bind G keys direct without having to add key combinations to them first.

**Comment by kylethedude5** [comment]
If you set your G keys to a hotkey macro and then use the same macro with Audioswitcher you can do this.  I have a similar setup with my Cyborg v.7 keybaord and I use two of the custom keys to change my audio device between speakers and a headset.

**Comment by xenolightning** [comment]
Pretty sure @Znubbis doesn't want to bind to a key combination mapped on the G-Key.

It might be an easy fix, but if I have to include a Logitech SDK just to use G-Keys this won't be implemented.

**Comment by xenolightning** [comment]
This requires the Logitech SDK. Will not be including it just to handle G-Keys.

Closing.

**Comment by Znubbis** [comment]
I can accept that, thank you for investigating.

**Comment by xenolightning** [comment]
NP, thanks for the request. Would've been a good one to include if it was standard functionality.

Even my CM Storm's macro keys don't work :(
