### ISSUE TITLE
WmiPrvSE.exe high CPU usage

### ISSUE THREAD

**Issue by lazahunter** [xenolightning/AudioSwitcher_v1#1614]
Hail!

If i runing the AudioSwitcher.exe, the WmiPrvSE.exe (Netword service) continually using hight cpu (~ 25-30%).

If i closed the AS, the WmiPrvSE.exe CPU usage 0%.

Win7, core i5-3570K, 8GB RAM

**Comment by xenolightning** [comment]
Is this on the new version?

1.6.7.96 / 1.6.8.99

There is a new feature which tracks Audio Sessions (similar to windows mixer), which hasn't been fully implemented yet.

**Comment by xenolightning** [comment]
Scratch that^

It's using 10%.

Thanks for the report. I'll get a fix in for it.

I've deprecated the most recent version due to a few issues arising.

I'd move back to 1.6.6.85 for now.

**Comment by xenolightning** [comment]
Resolved by removing WMI as per:

https://github.com/xenolightning/AudioSwitcher/commit/fd356f6b320755f98e8ec1d8147d303cedc4c8a5

**Comment by lazahunter** [comment]
Hi!

Thx for the quick reply :)

I used the version of 1.6.8.99.

Btw very useful app, i found it yesterday, with the app i can change between headphone and speekers quickly :)

Thx for the fix, i will test.

**Comment by xenolightning** [comment]
It's not released yet. This issue will be closed when it's included in the app.

Thanks for reporting the issue :)

**Comment by lazahunter** [comment]
Ok, i downloaded the older version :)

Have a nice day!

**Comment by xenolightning** [comment]
Should be fixed in 1.6.9.102
