### ISSUE TITLE
Running AudioSwitcher causes CPU to spike

### ISSUE THREAD

**Issue by guitarjorge24** [xenolightning/AudioSwitcher_v1#1679]
When I run AudioSwithcer my CPU goes from 6% to 26% and stays at 26% until I close AudioSwitcher. The process group responsible seems to be "Service Host: Local Service (Network Restricted)" which includes the process "Windows Audio". After I close AudioSwitcher, the CPU usage goes back to normal. Also, sometimes AudioSwitcher will freeze upon launch which also freezes the Windows audio controls. I'm using Windows 10 Build 10586.29 64-bit. I've been using AudioSwitcher for about half a year I think and this is the first time I'm encountering this issue. I'm not sure if the issue could be caused by Windows 10 but even using older versions of AudioSwitcher doesn't seem to fix this issue. I've also tried adding an exception for AudioSwitcher in my Antivirus program but it didn't fix it.
![service host](https://cloud.githubusercontent.com/assets/12472021/11842331/026ddedc-a3d1-11e5-8e38-a9021453f03d.png)

**Comment by xenolightning** [comment]
I have the same exact build of Windows 10 running on one of my test machines.

I'll investigate and update you on what I find.

Thanks!

**Comment by xenolightning** [comment]
I don't think it's the same issue as: #1614, but noting it just incase.

**Comment by benmcm1994** [comment]
I also still have this bug with the current version. It only recently started happening. Windows 10 64

**Comment by xenolightning** [comment]
@benmcm1994 Cheers for the heads up, if you'd like to raise a new issue and throw a few more details on the version + some details of the audio devices, that'd be ideal.

Thanks.
