### ISSUE TITLE
1.6.9.102 killing Windows Audio service

### ISSUE THREAD

**Issue by pcrov** [xenolightning/AudioSwitcher_v1#1680]
Running Audio Switcher 1.6.9.102 on Windows 10 terminates the Windows Audio service (leaving me with no audio devices.) If I restart the service it immediately shuts down again as long as audio switcher is running.

I'm *not* getting this problem with 1.6.6.85.

**Comment by xenolightning** [comment]
Does it happen instantly after starting Audio Switcher?

Is there anything in Event Viewer about the crash?

**Comment by pcrov** [comment]
Yes, it happens instantly. The Event Viewer simply shows an error with the message:

> The Windows Audio service terminated unexpectedly.

**Comment by xenolightning** [comment]
The only new addition is support for audio sessions, which is to come in a future version. It seems Windows 10 is a little touchy with audio devices.

This might also be related to: #1679

Use .85 for now, I'll see if I can get a beta version out later today.

Are you able to test a beta version, to make sure it's fixed?

**Comment by pcrov** [comment]
Yep, can do.

**Comment by xenolightning** [comment]
I've created 3 builds, with varying degrees of the audio session functionality removed.

Start at 1 -> 3 and see if any of them work.

If they continue to crash it, I'll have another look at it.

Thanks!


[AudioSwitcher_BUILD_1.zip](https://github.com/xenolightning/AudioSwitcher_v1/files/67649/AudioSwitcher_BUILD_1.zip)
[AudioSwitcher_BUILD_2.zip](https://github.com/xenolightning/AudioSwitcher_v1/files/67652/AudioSwitcher_BUILD_2.zip)
[AudioSwitcher_BUILD_3.zip](https://github.com/xenolightning/AudioSwitcher_v1/files/67653/AudioSwitcher_BUILD_3.zip)

**Comment by pcrov** [comment]
Build 1 still exhibits the problem, while both builds 2 and 3 function properly without issue.

**Comment by xenolightning** [comment]
Ok great, so that definitely confirms it's in the new Audio Session addition. Now the hard part is trying to find what's causing the issue.

The new session piece has been tested across Win7, Win8 and Win10. And hasn't seen anything like this.

Might need a little more information about the devices you have running on the system

**Comment by pcrov** [comment]
Audio devices are onboard audio (realtek) and a plug-n-play usb audio card that came with my steelseries headset. I'm happy to run a debug build that'll put together any sort of specific information you need, if you've got one.

**Comment by xenolightning** [comment]
Not sure if it'll be an easy bug to find.

AudioSwitcher isn't crashing which means it'll be very hard to get any sort of error out of it. I'll re-enable my onboard audio and see if I can get some sort o f reproduction.

**Comment by xenolightning** [comment]
It might be insanely silly, but could this be a driver issue?

Can you open Control Panel and do actions on the sound devices with it crashing?

http://www.sevenforums.com/sound-audio/328378-windows-audio-service-crashes-constantly-any-sound-action.html

Maybe see if there's an update for the Realtek audio drivers?

**Comment by pcrov** [comment]
Not silly at all, and it's something I should've checked first.

I had no problem performing actions on sound devices through the control panel or volume mixer, but I went ahead anyway and removed the existing realtek driver and installed the latest available from my motherboard manufacturer. (I neglected to note the old driver version though, sorry about that.)

Problem solved. 1.6.9.102 is functioning now without issue. Apologies for the noise.

**Comment by xenolightning** [comment]
Awesome! Saves me going back to the drawing board.

No apologies necessary, it's good to build a "wiki" of issues, now we both know if something similar comes up in the future updating drivers is the first step.

Glad it's all working for you.

There's a new version coming out soon which fixes a few minor issues with .102

https://github.com/xenolightning/AudioSwitcher_v1/milestones/1.6.10
