### ISSUE TITLE
Optimise Icon lifecycle & handles

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#1697]
Issue to track the release of https://github.com/xenolightning/AudioSwitcher_v1/pull/1692

Reduces the number of handles created when extracting icons from libraries.

Better manages the scope of the icons too.

**Comment by bitHero** [comment]
It looks like commit [this](https://github.com/xenolightning/AudioSwitcher_v1/commit/5ae7197487c8f86e197d7b5229c75350cca24ff7) commit fixed the issue. Are the development builds stable enough to run?

**Comment by xenolightning** [comment]
Yeah, anything currently in master @109 is stable enough for use.

The only planned changes between master and the next release will be an internal api update and a version bump.

Will close this issue when it get's tested alongside the changes above.

**Comment by bitHero** [comment]
Awesome! :+1:
