### ISSUE TITLE
iTunes Combatability

### ISSUE THREAD

**Issue by Birike** [xenolightning/AudioSwitcher_v1#1736]
I have a speaker and headphones connected to my PC, but the switcher will not change iTunes playback. Music from iTunes will always come out of my headphones, even if they are not the default device. The switcher works fine for everything else.

**Comment by xenolightning** [comment]
This is a choice within an application to opt out of the default device, and use it's own playback options.

I haven't used iTunes for many years, but from memory there is a setting in iTunes which allows you to play music through "Windows Audio Session", or something similar. You will need to enable that for iTunes to respect Windows audio settings.

Not an issue with Audio Switcher so closing.
