### ISSUE TITLE
Hotkey enhancement

### ISSUE THREAD

**Issue by supaethan** [xenolightning/AudioSwitcher_v1#1762]
Great little gadget!
As for now, If I need to switch between two devices, I need to press two sets of hotkeys, eg, alt+a for headset, alt+s for speaker. I wish I can just toggle between the favorite devices using one hotkey. Thanks!

**Comment by xenolightning** [comment]
Same as: https://github.com/xenolightning/AudioSwitcher_v1/issues/607
