### ISSUE TITLE
Renaming (add name) devices

### ISSUE THREAD

**Issue by nicolafarina** [xenolightning/AudioSwitcher_v1#1829]
Would be very useful to have a feature to rename (or add an additional name) to audio devices, because with some systems I have more devices with the same default name (f.e. High Definition Audio Device).

Thank you.

P.S. Great work, keep on coding!

**Comment by xenolightning** [comment]
There's a requirement for Audio Switcher to have admin privileges to do this (properly), so currently it's not available through Audio Switcher.

However! You can rename each device through Control Panel, and Audio Switcher will recognise and use these custom names.

Sounds > Playback Devices > Right Click on the Device > Properties - Change the value in the text box to whatever you like.

Closing for now, as it's not on the feature radar, and there is an easy "workaround"

**Comment by nicolafarina** [comment]
Wow, many thanks, I really didn't know about the renaming inside control panel.
