### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by rhaww** [xenolightning/AudioSwitcher_v1#1833]
Hello,
thanks for this great App! I have found out that it uses 1-2 % of my CPU also while minimized to tray. Maybe you have an explanation for this behavior or is it a bug with my machine only?
Thank you anyway!

**Comment by xenolightning** [comment]
It will use a minimal amount of CPU, even while minimized as the api monitors a fairly large set of system audio events.

Peak Meter, Volumes, Sessions, New Devices, Defaults to name a few.

I'm looking to improve the CPU usage, probably not in the next version but the one after.

The CPU usage is somewhat "false" too, as it's using timers which won't directly hold up and CPu operations

**Comment by xenolightning** [comment]
Actually, it will probably make it into the next release.

I found a simple way to reduce the overhead, and it brings the CPU usage down from about 1.5% to ~0.5%

**Comment by xenolightning** [comment]
![2016-01-12_17-17-03](https://cloud.githubusercontent.com/assets/6000196/12254926/227afeca-b953-11e5-848d-a3533eebd56c.png)
