### ISSUE TITLE
When I connect headphones they are displayed as Unknown

### ISSUE THREAD

**Issue by SimonCondon** [xenolightning/AudioSwitcher_v1#1870]
Hello, I would like to use this application, but it is not very useful to me if multiple devices are listed as unknown. Please help me resolve this.

Thank you,
Simon

<img width="590" alt="audio switcher" src="https://cloud.githubusercontent.com/assets/16812949/12472979/ef2f2834-c01e-11e5-80b4-6977b9c22dd3.PNG">

**Comment by xenolightning** [comment]
Can you check in Control Panel, to make sure the values are available? I assume they are, and it might be something to do with the way the device is loaded in Audio Switcher.

Example:

![2016-01-21_19-54-44](https://cloud.githubusercontent.com/assets/6000196/12473661/01e970ec-c079-11e5-8206-9270c939c615.png)

**Comment by SimonCondon** [comment]
Thanks for your quick response. Here's what i get:

<img width="663" alt="audio switcher2" src="https://cloud.githubusercontent.com/assets/16812949/12479241/e80e919e-c04a-11e5-8a29-8f14f2e34ecb.PNG">

**Comment by xenolightning** [comment]
Ok!

So it being a Bluetooth device might have something to do with it.

I think the device hasn't made it's "name" & "description" available when the device becomes "active". 

If you restart Audio Switcher, after connecting the headphones does it correctly show the names?

**Comment by SimonCondon** [comment]
Yes, if I restart AudioSwitcher after connecting the headphones, the names appear correctly.

**Comment by TimetravelerDD** [comment]
I have the exact same issue for approximatively 2 months. before it worked perfectly.
Not recognized is my USB Headset and my HDMI Receiver

**Comment by xenolightning** [comment]
Thanks for that, should be fairly easy to track it down and fix it.

Will post the updates here.

**Comment by xenolightning** [comment]
Have found whats causing it.

AudioApi is firing name changed events, before they are actually changed internally. The result is the name doesn't reflect the actual name (it's "one name behind" the actual).

Will fix it in the next version.

**Comment by SimonCondon** [comment]
Thanks for the update

**Comment by subochev** [comment]
The same issue with EMU 0404 USB audio card. You need to switch on the card before running Audio Switcher. Otherwise "Unknown". But hotkeys are working fine, it's good.

**Comment by AlkoSoul** [comment]
I've had the same issue with new devices being connected as "unknown", but it goes a little further than that (Version 1.6.10.113).

Basically, I unplugged my USB headphones to use the extension cable they are plugged into for something else (while the PC was running).  When I plugged the headphones back in and ran AS to change to the headphones, I got stuck in a loop of two errors.  Wish I'd taken screen shots of them as the meant nothing to me :(  Basically you'd click OK to one and the other would pop up - click OK to that one and the first would pop up.  I had to hard reboot the PC to get out of the loop.

I've tried a few times now to reproduce the problem, but I can't seem to do so (the most I get is "unknown" devices in the AS device list).  But I do notice that the keyboard shortcuts for the "unknown" devices are now missing from the list, but if I try and add them I get an error icon next to the shortcut saying the command is in use.  The only way to get rid of this error is to clear all shortcuts and set them up all again.

**Comment by xenolightning** [comment]
@AlkoSoul You've also uncovered this open issue here: https://github.com/xenolightning/AudioSwitcher_v1/issues/1253

There's no 'nice' way to handle this. Windows either treats the device as the same device and it works fine, or it will treat it as a new device, and things get screwy.

Arguably this isn't something that Audio Switcher should fix as there is no way to tell if a device is actually new, or (for example) is just plugged into a different usb port.

WiFi and Bluetooth devices are different again, some don't "disconnect" from the system at all. They stay in the system, but another connected flag arrived when the remote device is turned on. There's a lot of weird behavior for devices, handling them all is quite difficult.

**Comment by AlkoSoul** [comment]
Hi and thanks for the quick reply on this one.

As I've said in another post, I'm not great at programming / coding (just the basics is enough for me!).  However, I was thinking about this today, and was wondering if it's possible to register / log a device name in AS, as my USB headset always come up as "HP Premium Digital Headset".

If Windows 10 (or any other version of Windows) decides to call a device "unknown" as soon as it's plugged in, would it be an idea to get AS to re-scan / check the device after say 15 seconds to confirm it's ID / name - after all - people are not adding new audio hardware all the time.  I realise this sounds easy, but is probably a coding nightmare.  If it is possible, I'd suggest a maximum of 5 attempts to identify the device before giving up (or set an option in the AS setting to determine how many attempts to make).

As for "new" devices, I'd run through the repeat check-that-device-has-been-installed-before process above, and then resort to actually asking "Is this a new audio device?".  If you can make this work - I'd happily test it for you :)

Anyway, please forgive my lack of coding ignorance, and let me know what you think.

:)

**Comment by xenolightning** [comment]
@AlkoSoul You're on the right track with your thinking. 

Ideally you'd want it to work without "retry" logic in there. Which is where "events" come about, AS can subscribe to a notification from the hardware when device has changed it's name, and can get the new value for the name.

There is (currently fixed, but not deployed) a bug in the AS Api that would get these events, but wouldn't process them correctly. https://github.com/xenolightning/AudioSwitcher/issues/20

It's confirmed fixed from testing, so it will work as it should in the next release.
