### ISSUE TITLE
Switching works... Sometimes...

### ISSUE THREAD

**Issue by pjpeej13** [xenolightning/AudioSwitcher_v1#1871]
Ok, so I'm running AudioSwitcher v2.1 on Win10, and I'm running into an issue. For some reason, when I try to switch from my speakers to my headphones, and a youtube video is playing, the video sound stays on my speakers, but my headphones are considered the default. The only fix I could find is closing the youtube video window, switching, then reopening. Spotify works no matter what, even with a youtube video open. So spotify music would come through the headphoens after the switch, but youtube stays on speakers. Some games refuse to switch too, even if they're running in the background when I hit the hotkey. Is this a common issue? Windows reinstall changed nothing...

**Comment by xenolightning** [comment]
1. There is no version of this Audio Switcher that is 2.1. The latest of this one is 1.6.10.113

2. You should probably find the author of the tool you are using, and ask the question there.

3. Applications can opt into not using the "Default" for rendering audio. This is known as exclusive mode. This is common for things like Flash, or games over DirectX. There is no way to "fix" this, as it's desired behaviour.

**Comment by pjpeej13** [comment]
Wow you're right. I have 2 tools, both called audio switcher. I had the problem for both, and mixed up the two creators lol. The tool you created is running 1.6.10.113 on my system I believe. 

Well, if it'd desired behavior, I guess there's no point in trying to change it. Thanks for the help!

-pj

**Comment by xenolightning** [comment]
You can look into changing the game to use the Default audio, it might be an option in the sounds.

Same goes for the browser, have a google for it.
