### ISSUE TITLE
High CPU Usage while on Windows 7

### ISSUE THREAD

**Issue by TigerMonarchy** [xenolightning/AudioSwitcher_v1#1877]
I have a Dell Optiplex 280 and I have very high CPU usage rates when using Audio Switcher. I also use DFX Audio Enhancer and the app works relatively well with all of the pieces but I know in time it will better. But whether or not I use DFX, the main issue is the CPU load on my system when using the program. I'm on Windows 7 and use VLC and audio from Chrome primarily. I have USB headphones and normal integrated audio for the card. Any help with this would be greatly appreciated as otherwise the program is awesome and just what I've needed.

**Comment by xenolightning** [comment]
What version are you using?

The CPU usage has been reduced in the latest release.

**Comment by TigerMonarchy** [comment]
1.6.10.113 is the version I'm using. I'm sorry, I wasn't able to get to my
computer till now.

**Comment by xenolightning** [comment]
A few more details, and possibly some screenshots from Task Manager, or Process Explorer would be helpful.

Audio Switcher 1.6.10 should use more than about 0.5% CPU while minimized.
