### ISSUE TITLE
Numpad Keys recognized as alternative (left,right,home,end, etc)

### ISSUE THREAD

**Issue by archcorsair** [xenolightning/AudioSwitcher_v1#1887]
Was trying to set a hotkey along the lines of ctrl+alt+shift+numpad4 and instead of numpad 4 I get "left".

**Comment by xenolightning** [comment]
Heh, so it does!

Looks like it's the combination of Shift + NumPad that's causing it.

It's technically not a bug, and the hotkey still responds as intended, but it also responds to Ctrl + Alt + Left Arrow.

It seems the combination of Shift has the same affect of "temporarily" disabling Num Lock. This seems to be system-wide behaviour too.

I'd avoid any combination of Shift + NumPad to be safe.

I don't think I can fix this one either, is a pretty low level intervention to cause this (i.e keyboard driver/layout)
