### ISSUE TITLE
Windows 10 N turns off windows audio feature.

### ISSUE THREAD

**Issue by shadowsteppah** [xenolightning/AudioSwitcher_v1#1911]
![ss 2016-02-07 at 06 52 32](https://cloud.githubusercontent.com/assets/17105956/12871071/720c0588-cd67-11e5-91f4-2295cc225fd5.png)
When using audioswitcher it turns off windows audio services. After a short 15 minutes it will ramp up in cpu usage. 
![ss 2016-02-07 at 06 51 30](https://cloud.githubusercontent.com/assets/17105956/12871066/479917be-cd67-11e5-9d7d-b77f3b3b6c98.png)

**Comment by xenolightning** [comment]
What version of Audio Switcher are you using?

Have a check here: https://github.com/xenolightning/AudioSwitcher_v1/issues/1680

Something similar came up a little while back.

**Comment by shadowsteppah** [comment]
![ss 2016-02-07 at 06 56 57](https://cloud.githubusercontent.com/assets/17105956/12871083/0fd2a902-cd68-11e5-9858-18347f607509.png)

I am using the latest version.

**Comment by xenolightning** [comment]
Yeah it looks to be the same issue as #1680 

Try updating audio drivers, and see if it fixes it. There's a dodgy version realtek drivers floating around.

**Comment by shadowsteppah** [comment]
I will give that a try, and if it doesnt work I will use the other builds linked in #1690

**Comment by shadowsteppah** [comment]
I have currently switched over to Build two from #1680 as installing the newest realtek drivers as found on the manufacturers didnt fix the issue.
![ss 2016-02-08 at 02 59 51](https://cloud.githubusercontent.com/assets/17105956/12877246/a86f667a-ce10-11e5-8f46-0a13a7b2396d.png)

**Comment by xenolightning** [comment]
I'd roll back to 1.6.6.85, instead of the debug build in 1680.

I'll keep this open to track the issue, but I think it's some combination of Realtek + Windows 10 that's causing the problem.

Until I get my main dev machine running Win10 I won't be able to investigate the issue any further.

**Comment by xenolightning** [comment]
This should be improved in 1.6.11 and above.

The audio session functionality that causes this weird behaviour has been put into a delayed initialisation state.

Effectively it means it's not created until it's requested. Audio Switcher 1.x doesn't request audio session functionality so it should go back to normal. 

As a side effect the CPU usage also drops by about 3/4, however 1/4 of about 0.1% isn't very much at all.

**Comment by xenolightning** [comment]
If you want to try an early release candidate and see if it fixes the issue that'd be great.

It's attached in this comment. 1.7.0.116

All going well it should be released later this week.

[AudioSwitcher.zip](https://github.com/xenolightning/AudioSwitcher_v1/files/132237/AudioSwitcher.zip)

**Comment by shadowsteppah** [comment]
Nice thanks! So far so good. CPU Usage is stuck at 0%, it works flawlessly. I will get back to you later down the week if I run into something.

**Comment by groove200** [comment]
I had the same problem , your rc seems to fix the problem :-)

Thanks
