### ISSUE TITLE
Remove Hotkeys from Previously Removed Devices

### ISSUE THREAD

**Issue by archcorsair** [xenolightning/AudioSwitcher_v1#1984]
I'm experiencing an odd issue, I purchased a new soundcard - so all new outputs/inputs. However, since my old device is no longer present I cannot remove it's assigned hotkey. 
![image](https://cloud.githubusercontent.com/assets/1036921/13380958/0210202c-de04-11e5-9f42-4839a26e2e54.png)

**Comment by xenolightning** [comment]
Yeah Audio Switcher still thinks the hotkeys are registered. Bit of a limitation of the code here.

If you click the clear all button, it will remove the hotkeys, including the ones that are "hidden", and you can re-create them for your new devices.
