### ISSUE TITLE
Wireless headphones stopped working after uninstall; other related bugginess.

### ISSUE THREAD

**Issue by heofenum** [xenolightning/AudioSwitcher_v1#1985]
I previously uninstalled this from my Win 7 desktop since it wasn't always working. When I restarted my comp immediately after (because I also chose to relocate the computer immediately after) the volume icon in the tray had disappeared and I had to re-enable it in windows. Then i noticed my headphones stopped working. They still work on my Win 10 laptop; nothing is wrong with the headphones. I have uninstalled and re-installed the headphone driver (Turtle Beach Stealth 450), and I even re-installed AudioSwitcher. I know some components of it had not fully uninstalled previously, because when I went to set the same hot key I previously used for these headphones (ctrl+alt+H), it said "Hot key is already regsitered".  Re-installing AudioSwticher didn't magically fix the issue, and I should add that I probably plugged the USB hub into a different USB port ater I moved the computer.
Given the timing and other details, the issue is either related to AudioSwitcher, in which case I need to find to remove it and all components thoroughly), or because I moved it to a different USB port. Could that really be the issue though? Please help. This has ruined the utility of these pricey headphones on my primary machine. Thanks

**Comment by xenolightning** [comment]
Audio Switcher doesn't "install" anything on the machine. And this certainly doesn't sound like something that Audio Switcher could even do.

It creates a single configuration file, that is located in C:\Users\*USER*\AppData\Local\AudioSwitcher

Outside of that configuration file, if it is not running it will not have any affect on the system **at all**.

Feel free to remove the configuration file, for completeness, but it won't be stopping your headphones from working.

You should probably contact the manufacturer of the headphones. They will be able to provide better support for the issues you are experiencing.
