### ISSUE TITLE
Setting Default Device throws error

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#2007]
### Details:

Audio Switcher
Version: 1.7.0.117
Operating System: Microsoft Windows NT 6.2.9200.0 64-bit
Administrator Privileges: False
### Stacktrace:

```
System.TimeoutException: COM operation 'SetDefaultDevice' did not complete in the requested time period.
   bei AudioSwitcher.AudioApi.CoreAudio.CoreAudioDevice.SetAsDefault(CancellationToken cancellationToken)
   bei FortyOne.AudioSwitcher.AudioSwitcher.notifyIconStrip_ItemClicked(Object sender, ToolStripItemClickedEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnItemClicked(ToolStripItemClickedEventArgs e)
   bei System.Windows.Forms.ToolStripDropDown.OnItemClicked(ToolStripItemClickedEventArgs e)
   bei System.Windows.Forms.ToolStrip.HandleItemClick(ToolStripItem dismissingItem)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by xenolightning** [comment]
This is proper feedback from devices that cannot be set as defaults.

It should not throw an error message to the user though.

Look at either suppressing the error or introducing a dialog.

**Comment by vlakoff** [comment]
I encountered this error *once*, while my system was exceptionally busy. Otherwise doing the same operations I don't encounter it.

So maybe actual timeout may happen too :) But as I said it was really exceptional, and catching the exception would be only cosmetic for this case.

**Comment by xenolightning** [comment]
Yeah it's caused by either the Api having a queue of messages and it hasn't processed the request to set a default before the automatic cancellation, or the system hasn't returned a message to say the default has been changed in the time period requested.

It's not very common, but doesn't happen infrequently when there are a few hundred thousands users of Audio Switcher.

Suppressing the error message is the best approach as it's not an unexpected error, and it doesn't even mean that the system didn't change the default device.
