### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by NLCJ** [xenolightning/AudioSwitcher_v1#2122]
Today I suddenly noticed that AudioSwitcher was switching slowly (more than 10 seconds) between my audio devices. Upon looking at my resource usage I noticed that my memory (6GB) was at 100%, after closing AudioSwitcher it went down to about 2.4GB in use.

Perhaps it might be due to my PC mostly being put to sleep instead of rebooting.

**Comment by xenolightning** [comment]
What version are you using?

**Comment by NLCJ** [comment]
Sorry, I completely forgot about this. I was using version 1, but cannot tell you the specific version number (the program told me there was an update and I installed it). I am now on 1.7.0.117 and will see if it is still present.

**Comment by xenolightning** [comment]
It was certainly an issue in the previous verion. See #1900 for a big discussion on it.

It's fixed as of 1.7.0 and later though.
