### ISSUE TITLE
Volume slider for enabled audio device

### ISSUE THREAD

**Issue by Burn0matic** [xenolightning/AudioSwitcher_v1#2124]
basically it would be nice to have a volume slider  to be able to slide the volume on the selected audio device.

much like this other audio switcher app i have found https://github.com/sirWest/AudioSwitch
if you scroll down a lil bit you will see the how the volume slider is set up , right in the right click audio device selection area.

thanks guys for all the hard work really appreciate it and i love love these lil apps.

**Comment by xenolightning** [comment]
Not some I will make available by a UI.

It can be done by scripts in v2.0, but it's not meant to replace the existing mixer.

A combination of media keys, or the standard Windows Mixer fulfills this functionality fairly well.

I do have plans to build an alternative to the Windows mixer in the near future. Which will also allow programs to play sound through "non-default" devices too.
