### ISSUE TITLE
Feature request - set icon for each favorite output device

### ISSUE THREAD

**Issue by VictorZakharov** [xenolightning/AudioSwitcher_v1#2127]
New option: right click on any device on Playback tab - add option to "Set icon > ...", speaker, headphone, default (note) and custom - being able to specify any custom icon.

Should not assume headphones icon for headphones (as told by the system). Could be anything, so just a config, for which the default would be current behavior. User then can decide to change icon for certain devices, when they are currently selected.

Right now impossible to tell what's playing.

**Comment by xenolightning** [comment]
Audio Switcher by default respects what Icon is set in Windows.

You can change the icon that the device uses through Control Panel, and Audio Switcher will use this icon.

Control Panel > Sounds > Playback > Right Click Device> Properties > Change Icon

**Comment by VictorZakharov** [comment]
No I meant the tray icon. Right now it's always the same - blue note. Would be nice to see whether it's headphones or speakers.

**Comment by xenolightning** [comment]
Enable the "Show Default Playback Device icon in tray" setting.

**Comment by VictorZakharov** [comment]
Ok, now it's much more functional. There is a problem however. In Sound panel background color is white, so black on white looks good (my system icons). My taskbar is dark blue, so the same icons are hardly noticeable. It would be better to have icons/artwork from the same designer who created the "blue note" icon, which is currently the default. Maybe for other people it would make sense to also set color palette, so keep blue as default, but make it possible to set green, red etc. specifically for tray icons. I think it could greatly enhance UX.

**Comment by xenolightning** [comment]
Yeah I've noticed the same thing. Especially with WIndows 10, the default Headphone icon is quite difficult to see. 

It's unlikely that this change will go into 1.x, but is a good candidate for exploration in 2.0.

I'll raise something to track it's progress.

**Comment by VictorZakharov** [comment]
Thank you, Sean.
