### ISSUE TITLE
Doesn't want to start on Windows Start Up

### ISSUE THREAD

**Issue by billy80808** [xenolightning/AudioSwitcher_v1#2129]
The first week of downloading AudioSwitcher (ver. 1.7.0.117) it worked perfectly fine.  Then it just stopped opening on start up. Start on start up box is ticked still.  Anything i could try to get it working properly again?

**Comment by xenolightning** [comment]
What version of Windows?

There might be another application affecting the start up. You can recheck the setting in Audio Switcher and it will add itself back into startup.

If that doesn't work I suggest you have a look at how to configure startup items in Windows. Google is probably the best "man" for the answer.

**Comment by billy80808** [comment]
I actually found a somewhat long way around it to force it to open but i
think the problem was with administration access since it asks if you want
to open it before it runs and most times it doesnt even ask so it never
opens. But, the way around it is:
Creating a task for it on start up
Put the program on a whitelist
Create a shortcut icon for that task
Move the task shortcut into the startup folder

That way itll start up without prompt and start on windows start up! Works
every time so far without issue

**Comment by xenolightning** [comment]
Ahhh! Nice one!

Yeah, the startup folder is a good solution. Seems like it's still a standard way of creating some startup items. 

The registry is a "cleaner" way of doing it, but access to the registry is generally restricted to apps running as admin, which Audio Switcher (ideally) shouldn't be doing unless absolutely necessary.

I might look into improving the startup code, surely there has to be a better way of doing it!
