### ISSUE TITLE
Macro keys as hotkeys

### ISSUE THREAD

**Issue by dat--guy** [xenolightning/AudioSwitcher_v1#2130]
First of all this is a great little app. However, I'm not sure if it is just the keyboard I am using (Razer Blackwidow), but the macro keys do not seem to work as hotkeys.

It would be great it these could be used as hotkeys. I understand that this is a very small issue, so no worries if you don't plan on adding this anytime soon!

**Comment by xenolightning** [comment]
There was a request for this on Logitech keyboards, and something tells me that I had to include the Logitech SDK to detect them.

I have a Razer Blackwidow, so can see what it produces.

My gut feeling is that it will require an SDK too. Will update the issue with my findings.

**Comment by danielbibit** [comment]
Assing any combination to the hotkey, and then bind this combination to the macro switch using whatever resource your keyboard have. Did the trick for me.

**Comment by xenolightning** [comment]
Third party keyboard support requires drivers/libraries. 

As mentioned a good solution is to map the macro key to a key combination, and use that combination as the hotkey in audio switcher.
