### ISSUE TITLE
Ability to set hotkey for Default Device and Default Communications Device

### ISSUE THREAD

**Issue by deviant749** [xenolightning/AudioSwitcher_v1#2131]
I use an Astro a40 headset and use audioswitcher to switch between it and my speakers.  However, to use its game/voice mixamp, I have to set two devices, the default communcations device, and the default playback device.  I'd like to be able to set a hotkey to do each of these things, currently the hotkey interface just sets a device and a hotkey, and it sets either as default, or dualswitches if the appropriate toggle is on.

Example:
Ctrl+Shift+1 sets Device X as default Communications Device, and Device Y as Default Device
Ctrl+Shift+2 sets device Z as both.

**Comment by xenolightning** [comment]
Ability to this is covered under 2.0, with it's scripting support you can create different "profiles".
