### ISSUE TITLE
Hotkey In Use

### ISSUE THREAD

**Issue by Stinkyshew** [xenolightning/AudioSwitcher_v1#2133]
Lately I have been having trouble assigning Alt+F2 as a hotkey, as it says it is in use. I have cleared all hotkeys and deleted the .json in appdata as well hoping it would clear the hotkey, but no such luck. It was working previously, but I am not sure what I did, or maybe if because I have unplugged and plugged in that device it has messed something up. If you have any ideas please let me know. 

Thanks

**Comment by xenolightning** [comment]
Sometime the hotkeys can get "stuck".

To reset them for good:
1) Clear all Hotkeys from AudioSwitcher (button on the Hotkeys tab)
2) Close AudioSwitcher
3) Restart Windows

Restarting Windows will remove any registered hotkeys from the system, sadly there's no other way to remove "forgotten" hotkeys.

**Comment by Stinkyshew** [comment]
Hmm that still didn't clear the key. It's only not clearing Alt+F2 as well. Not a big deal as I can just assign a different key, but do you happen to have another idea that may clear it?

**Comment by xenolightning** [comment]
The hotkeys are globally registered so another application may also have it registered.

Check out http://www.nirsoft.net/utils/hot_keys_list.html

It gives a list of all the hotkeys registered, by all applications.

See if anything registers that particular hotkey, even when AudioSwitcher is closed/hasn't started.

**Comment by Stinkyshew** [comment]
Oh I didn't realize that, thanks for linking that, I guess it is in use by something else. Thanks for all your help.

**Comment by xenolightning** [comment]
No prob! :+1: 

There are other ways of doing the hotkeys, but they appear as "viruses" (keyloggers) which isn't ideal :smile:

**Comment by jaredbaszler** [comment]
I've having issues with this.  I have a hotkey that I assigned through Audio Switcher and it seems to be stuck but not showing up or functioning like it should.  

Alt-Up used to be my hot key to switch to my USB Sound Bar:

![image](https://user-images.githubusercontent.com/9924084/29123870-cb279e0e-7cdc-11e7-8ef6-602a7119ec97.png)

But you can see in the image above Alt-Up is on the list of registered hot keys but it is not on the list within Audio Switcher.  If I close Audio Switcher then Alt-Up goes away.  When I open Audio Switcher, it returns to the list in HotKeysList:

![image](https://user-images.githubusercontent.com/9924084/29123962-124cd164-7cdd-11e7-890a-712d7e774354.png)

This makes me certain that Audio Switcher is in control of the Alt-Up hotkey.  

I've deleted all my hot keys within Audio Switch and restarted.  Same behavior still exists.  

Any thoughts would be appreciated.  Thanks.

**Comment by xenolightning** [comment]
@jaredbaszler Sometime hotkeys can get "stuck" in the configuration file when a device disconnects.

You can clear them out manually and restart audio switcher. Doing this will stop Audio Switcher registering that hotkey on startup.

Check out the wiki, some great instructions were put together by @vlakoff

https://github.com/xenolightning/AudioSwitcher_v1/wiki/Manually-Reset-Hotkeys

**Comment by vlakoff** [comment]
Actually I just added the "updates" part at the bottom of that page.

That page would probably better be reduced to something simpler, like "You switched your sound adapters and now it doesn't work? Just click on the "clear all" button."
