### ISSUE TITLE
Switching to USB audio devices disables USB mouse

### ISSUE THREAD

**Issue by lamkindt** [xenolightning/AudioSwitcher_v1#2135]
Whenever I switch to my USB audio device (The headphone jack on my Blue Yeti microphone) my mouse stops working. Once I switch back to my HDMI monitor as the audio output device, my mouse starts functioning again. Any ideas?

**Comment by xenolightning** [comment]
Try it through control panel and see if it still does it.

When switching devices AudioSwitcher doesn't really do anything control doesn't.
