### ISSUE TITLE
Hotkey to change only the recording device

### ISSUE THREAD

**Issue by hhiru** [xenolightning/AudioSwitcher_v1#2144]
I do not know if this is a bug or a missing feature but I'm trying to switch default recording device using hotkeys but whenever I use the hotkey windows set the recording device as a playback device. I have different recording devices linked and I just want to switch the default one with hotkeys, how do I do that?

**Comment by xenolightning** [comment]
Can't do it with one hotkey, can only set one device per hotkey.
