### ISSUE TITLE
Is there a trick to getting started?

### ISSUE THREAD

**Issue by hvyweight** [xenolightning/AudioSwitcher_v1#2149]
Hi, I'm running Windows 7 Pro (64-bit) and 1.7.0.117. I'm generally pretty tech savvy, but I can't get Audio Switcher to work. I've tried various hotkey combinations, and nothing seems to work. Is there some basic guideline or instruction that I'm perhaps missing?  (Sorry if this isn't the space for this type of problem).

I love the idea! I'm on the phone in my office all the time - generally using a microphone / webcam / speaker. But occasionally need to quickly switch to a headset - and this is perfect.

My system is a i5-3470 running all standard drivers.

Thanks!

**Comment by xenolightning** [comment]
There shouldn't be any tips or tricks you need to get it working.

Does a manual switch via the UI work? / Is it just hotkeys that aren't working?
