### ISSUE TITLE
Option to override setting a hotkey already in use?

### ISSUE THREAD

**Issue by ShadowOfADoubt** [xenolightning/AudioSwitcher_v1#2150]
Is there a workaround that allows this? Sorry if this is the wrong place for this.

**Comment by xenolightning** [comment]
The hotkeys are registered globally, for all applications.

So if another application has the hotkeys registered there's no way to override it.

If it was Audio Switcher that registered the hotkey in the past, using clear all, and restarting Windows will remove all hotkeys.
