### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by rsewalsh** [xenolightning/AudioSwitcher_v1#2151]
Please let me know how to uninstall Audio Switch 1.7.0.117 from Windows 10.  Thanks!

**Comment by xenolightning** [comment]
It doesn't install anything, so you can just delete the exe, and it's gone!

**Comment by backslashV** [comment]
it stays in task manager's startup tab even after removing the exe!

**Comment by xenolightning** [comment]
@backslashV 

If you use the open on startup setting, it will create a startup registry entry to reflect that.

You can either uncheck the setting or remove the registry entry manually to remove it from the startup list.
