### ISSUE TITLE
Timout error on startup

### ISSUE THREAD

**Issue by nathan323** [xenolightning/AudioSwitcher_v1#2152]
On startup of OS, recieve following message:

    System.TimeoutException: COM operation 'SetDefaultDevice' did not complete in the requested time 
    period.
    at AudioSwitcher.AudioApi.CoreAudio.CoreAudioDevice.SetAsDefault(CancellationToken 	
    cancellationToken)
    at FortyOne.AudioSwitcher.AudioSwitcher.Form_Load()

AudioSwitcher v1.7.0.117
Windows 7, SP1
2 devices:
    Realtek HD Audio 2nd Output
    Panasonic-TV-8 (NVIDIA High Definition Audio)

**Comment by xenolightning** [comment]
This is caused by the system not being ready to switch the sound devices yet.

Nothing to worry about, and can happen from time to time.

You can happily ignore the error :)
