### ISSUE TITLE
Suggestion: Add favourite switching functionality to hotkey

### ISSUE THREAD

**Issue by pcprince** [xenolightning/AudioSwitcher_v1#2154]
Having multiple buttons assigned to switch between a fixed set of devices is a minor annoyance. The ability to left click the tray icon to switch between favourites is useful for this, so my suggestion is the ability to assign this functionality to a hotkey.

**Comment by xenolightning** [comment]
Check out: https://github.com/xenolightning/AudioSwitcher_v1/issues/607
