### ISSUE TITLE
Bluetooth Issue

### ISSUE THREAD

**Issue by MZik** [xenolightning/AudioSwitcher_v1#2156]
I have a bluetooth adapter plugged into USB, and I turn on my Powerbeats 3 midday - but for some reason the hotkey disapears after I assign it (I assume since the device wasn't recognized when the program booted?)

Then to re-assign hotkey, I have to clear all. 

https://media.trillian.im/media/?m=aW1hZ2UvcG5nLDEwMTYsNDAwLAwTZ%2BguJY9XpXt4iuosaYSqKpnmZxhmVmSEBCLE%2Fgf2

So in the end, it takes the hotkey functionality away from it due to this error, and I have to clear / reassign all everytime. Love to hear your thoughts!

**Comment by xenolightning** [comment]
Have a look at this issue: https://github.com/xenolightning/AudioSwitcher_v1/issues/2123

There's a limitation within Windows; when reconnecting devices it thinks it's a new device every time, and gives it a new identifier, which then invalidates the hotkey.

Clearing all is sadly the only workaround for this, without somehow matching on device name.
