### ISSUE TITLE
Duplicate hotkey detected

### ISSUE THREAD

**Issue by iddo12** [xenolightning/AudioSwitcher_v1#2157]
Hi,
I am using Audio Switcher and love it but it does give me some issues with hotkeys. 
I am using win 10 and the latest Audio Switcher version and I am trying to set 2 hotkeys but it keeps saying that they are taken although an hour ago they worked fine until I unplugged one of the devices (Scarlett solo) and re-connected it and now I can't go back to my original hotkey - alt and minus sign - it is as if this key is now taken - is there a way to clear this up?

On the same note - is there a place in windows to see all the occupied hotkeys and what they do? (not just for windows but for all programs that work on windows and run at a given time).

Thanks!
Iddo

**Comment by xenolightning** [comment]
It was most likely caused by Audio Switcher registering a hotkey against a device that is no longer plugged in.

You can use the clear all button and restart AudioSwitcher/the PC, and it should work as expected again.
