### ISSUE TITLE
Quick switch no longer works after Windows 10 Creators Update

### ISSUE THREAD

**Issue by forgoodguy** [xenolightning/AudioSwitcher_v1#2160]
Audio Switcher version: 1.7.0.117
OS: 	Microsoft Windows 10 Pro version 1703
(Version: 10.0.15063 Build 15063)
Sound: AMD High Definition Audio Device
Headset: Logitech H820e

Hello. 

Thank you for the so useful tool! I use it every day at work. The quick switch is essential to fast operation.  I switch between the speakers and the headset. Unfortunately right after the  Windows 10 Creators Update the quick switch feature no longer works with the left click.
Wondering if you could look into this?

Thanks!

**Comment by bondt** [comment]
@forgoodguy, have you checked that the devices are still marked as favourites?

**Comment by forgoodguy** [comment]
@bondt, thank you for the quick response. Thas was the issue. Not sure how/what removed the favorite assignments...
