### ISSUE TITLE
Hot keys not saving

### ISSUE THREAD

**Issue by BlinkPro** [xenolightning/AudioSwitcher_v1#2161]
Audio Switcher version: 1.7.0.117
OS: windows 7

So I had audio switcher for ages and it worked perfectly. Then all of a sudden it stopped saving my hot keys after a reboot. I think it might be something to do with the folder that contains the hot key saves being read only. (a problem i have had with a few other programs, i think it started when i changed the drive my OS was on)
I dont know where it saves these so havent been able to test my theory. The only thing that makes me think this isnt the issue is that after reboot, and the hot keys arent working, I try set the same hot keys and it says that those hot keys are already registered (although the hot key list is blank). I have to clear hot keys and then all works fine until the program is closed and restarted. 

any help would be amazing!

**Comment by Xamantu** [comment]
Same thing happens here.

OS: Win 10, for me.

**Comment by xenolightning** [comment]
It might be a permissions issue (shouldn't be though)

Settings are stored in `<user profile>\AppData\Local\AudioSwitcher\AudioSwitcher.json`

Check out this wiki page for more info: https://github.com/xenolightning/AudioSwitcher_v1/wiki/Manually-Reset-Hotkeys

See where you get with that.

If you favourite the devices, is it saving this through a reboot?

**Comment by BlinkPro** [comment]
Well I changed the folder permissions and favorited the devices and that seems to have sorted the issue! 
Thanks for the help!

**Comment by xenolightning** [comment]
Awesome.

What were the folder permissions set to? Read-only or something?

**Comment by Xamantu** [comment]
I didn't change folder permissions, favoriting the devices fixed it already.
