### ISSUE TITLE
"System.NullReferenceException" in AudioSwitcher.AudioApi.CoreAudio.dll

### ISSUE THREAD

**Issue by EverBS2014** [xenolightning/AudioSwitcher_v1#2162]
I'm using VS2017 on Windows 10. My WPF application is using the lastest version of this API and has a Realtek onboard sound card

I want to set the volume of the windows setting to max like that:

```
 CoreAudioDevice defaultCaptureDevice = new CoreAudioController().DefaultCaptureDevice;
 defaultCaptureDevice.Volume = 100;
```

So far it's working but after the first call my CPU usage is increasing and I constantely receive this message in the VS2017 output window:

> "System.NullReferenceException" in AudioSwitcher.AudioApi.CoreAudio.dll
> "System.NullReferenceException" in AudioSwitcher.AudioApi.CoreAudio.dll
> "System.NullReferenceException" in AudioSwitcher.AudioApi.CoreAudio.dll
> "System.NullReferenceException" in AudioSwitcher.AudioApi.CoreAudio.dll
> "System.NullReferenceException" in AudioSwitcher.AudioApi.CoreAudio.dll
> "System.NullReferenceException" in AudioSwitcher.AudioApi.CoreAudio.dll
> ....
> 

It's not stopping. What is wrong?

**Comment by xenolightning** [comment]
Can you open it in the Api project? https://github.com/xenolightning/AudioSwitcher

With specific details on the version, and OS version?

Thanks.

**Comment by EverBS2014** [comment]
I have downloaded your link, but which project do I have to start? I tried to build all with VS2017 but I get several errors

I'm using AudioSwitcher.AudioApi.CoreAudio. 3.0.0.1 And I have to problem with Win 7 and Win 10

My WPF application has as target framework .NET 4.5.2

**Comment by xenolightning** [comment]
Sorry. I meant open the issue in the Api Project. This project is for the desktop application.

Can you try using the latest version 4.0 alpha build instead of v3.0.0.1?
