### ISSUE TITLE
Audio cuts off / Browser gets stuck when switching from Headset to Speakers using shortcut

### ISSUE THREAD

**Issue by sata67** [xenolightning/AudioSwitcher_v1#2165]
Audio Switcher version: 1.7.0.117
Operating System: Windows 10 Retail 64bit version 1709 build 16299.125
Audio devices on the system: Logitech Z623 2.1 Speakers, Corsair VOID RGB USB Headset
Sound card:  Creative Sound Blaster Z 5.1, driver version: not sure where to check this

The issue happens when quick switching (using the selected hotkey) between Headset and Speakers (Might be the other way around too, cant remember)
---------------

I have set shortcuts Ctrl+1 for my speakers and Ctrl + 2 for my headset (not the numpad ones, the number keys below the F keys)

This issue happens only sometimes, not every time. When it does, then when clicking Ctrl+1 to switch sound from Headset to Speakers, or when clicking Ctrl + 2 to switch sound from Speakers to Headset, and I have a live stream open in Firefox, plus a music player program open (both playing and have sound), then Audio cuts off, sometimes only of the stream and sometimes only of the music player program, and I have to reopen the tab, or restart the music program, or both. for them to play sound again.

Today it was worse, I had to restart the computer (restarting the browser or music player program did not work, I ended the tasks, and could not even reopen them... I have no idea what is the problem here...

Edit:
 I forgot to mention that the speakers sometimes go in standby mode when im using the headset (like after 2 hours or so) maybe this has something to do with the issue

Edit: This seem to happen when manually switching (clicking on the speaker tray icon and selecting the playback device) so it seems the problem is different.
I will try and resolve this (any suggestions are appreciated)

**Comment by xenolightning** [comment]
Hey, apologies for the slow response.

It does sound like something regarding you specific devices, rather than Audio Switcher.

I have seen this in the past, where some applications lock up when switching audio devices when there is sounds actively playing. I had seen this in firefox, with youtube playing in html5 and flash.

I don't know of any immediate solution, possibly switching without sound playing may work for you.
