### ISSUE TITLE
where are the shortcuts saved?

### ISSUE THREAD

**Issue by claudiopj** [xenolightning/AudioSwitcher_v1#2166]
Not a problem but a question.

I have created shortcuts for the sound and would like to know where the shortcuts are saved. I had to install windows again and I was forced to re-create all the shortcuts.

**Comment by xenolightning** [comment]
What shortcuts?

Audio Switcher doesn't create any shortcuts?

**Comment by xenolightning** [comment]
Oh you mean hotkeys?

**Comment by claudiopj** [comment]
​if I create shortcuts to the sound device, somewhere should they get
saved, right?​



On Jan 14, 2018 17:59, "Sean Chapman" <notifications@github.com> wrote:

What shortcuts?

Audio Switcher doesn't create any shortcuts?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xenolightning/AudioSwitcher_v1/issues/2166#issuecomment-357537679>,
or mute the thread
