### ISSUE TITLE
Favorites / Hotkeys not saving on restart for nVidia HDMI audio device

### ISSUE THREAD

**Issue by levinium** [xenolightning/AudioSwitcher_v1#2167]
- Software Version: 1.7.0.117
- Windows 8.1
- PC sound card, Nvidia HDMI audio, realtek digital output
- nVidia Version: 381.89

I have the app set to run on startup. For some reason on every restart I lose the HDMI as a favorite device and have to set it again. Could it be because the hdmi cable is unplugged? If so can it remember the device and set it as a favorite again once it's plugged back in? It looks like also my hotkeys for the HDMI device don't save on restart either, maybe for the same reason (if that is the reason).

**Comment by xenolightning** [comment]
Yeah, if the hotkeys/favourites aren't saving for a device it's because Windows is treating it as a different device each time.

This would require switching by name, or something different. 

Not on the radar to fix for 1.0.
