### ISSUE TITLE
Suggestion: Play sound when switching devices

### ISSUE THREAD

**Issue by CyberBlade007** [xenolightning/AudioSwitcher_v1#2168]
Please ensure you include/confirm the following information before submitting an issue.

- [ ] I have listed the Audio Switcher version
- [ ] I have listed my operating system, and version
- [ ] Include any details about the audio devices on the system
- [ ] If you are using Nvidia or AMD for sound, include the driver versions
- [X] This is not an issue about setting more than one device as default from a hotkey, quick switch or other relating switching activity.

And do remember this application is developed and distributed **FOR FREE**, you should have no expectation that an issue will be fixed in a reasonable time-frame.

I use audio switcher frequently to switch between my TV speakers and my computer speakers, sometimes my headset. It works great haven't had any issues with it. I did have one suggestion, I was wondering if you could make it play a sound after you have switched the default device. It would be similar to the sound that plays when you change the volume on your computer. I find that every time I make the change, I open the volume slider and ding it just to make sure audio is coming from the correct location. It would be nice to eliminate this extra step. I apologize if this has been brought up before, I attempted a search but was unsuccessful in locating anything similar.

**Comment by xenolightning** [comment]
Yup, is a good idea, duplicated here #219 

:)
