### ISSUE TITLE
how to restore hotkeys

### ISSUE THREAD

**Issue by claudiopj** [xenolightning/AudioSwitcher_v1#2170]
Hi, 

I'm having a problem restoring hotkeys in **windows 10.** I **found json** and inserted 

it in the correct folder. However, as you can see in the attached image, they do not appear and do not respond when I send a command. 

When I right-click on the icon of the program the list of available audios appears

IMAGES

![000](https://user-images.githubusercontent.com/7318276/38398368-6efacfb2-3919-11e8-98c7-f8462c6285e2.jpg)
![001](https://user-images.githubusercontent.com/7318276/38398369-6f1eba6c-3919-11e8-9f78-385acf1034ec.jpg)
![002](https://user-images.githubusercontent.com/7318276/38398370-6f43c730-3919-11e8-93d7-956ef074dab1.jpg)

JSON 

[AudioSwitcher.txt](https://github.com/xenolightning/AudioSwitcher_v1/files/1882268/AudioSwitcher.txt)

**Comment by xenolightning** [comment]
It might be caused by the devices changing Id's?

Try out the new "Show Unknown Devices in Hotkeys" setting, which will display "invalid hotkeys", which can then be updated.

**Comment by claudiopj** [comment]
Hi, it worked.

The id's must have been changed.

However, every time Windows 10 updates I have to do it this way? It would be rather laborious.

I am an insider tester of windows 10 and there is always an update.

But this solution makes work much easier.

Thank you so much

**Comment by xenolightning** [comment]
Sadly there's no work around.

Windows treats them as new devices which invalidates the old hotkeys, and I guess that's also the case after an update on the insider ring.

Not sure if it's also the case on the normal update chain, I haven't run into it yet.

**Comment by claudiopj** [comment]
thank you for your help and God bless u
