### ISSUE TITLE
Startup with Win not working 

### ISSUE THREAD

**Issue by vanjasmailovic** [xenolightning/AudioSwitcher_v1#2171]
Audio Switcher version: 1.8.0.142
OS: Win8.1 Pro, 64-bit 
Audio devices: Roland Quad-Capture with two selectable stereo outputs
Issue: 

Although selected, the AudioSwitcher does not **startup** with Windows.  :confused: 
Tried selecting different Compatibilities options under Properties of the .exe files (such as _Run for Win7_, _Run As Administrator_ and these two in combination with _Change settings for all users_) to no avail. 

![startup](https://user-images.githubusercontent.com/31690476/38525396-6b10da40-3c52-11e8-9939-fb2b57fa5b6f.png)

**Comment by xenolightning** [comment]
Could there be an anti virus, something else preventing start up?

Given that it's listed in the start up on task manager it should work as expected.

Is it still in the start up list after a reboot?

**Comment by sambul13** [comment]
@vanjasmailovic 

Check with Sysinternals Autoruns, if AudioSwitcher is auto-launched. Also, when antivirus starts after user login to Windows, it may prevent or delay other programs start. Its usually fixable after a few reboots as the boot sequence gets prefetched, though depends on OS version.

**Comment by vanjasmailovic** [comment]
Working after a few reboots, must be the AV then, as advised. Thanks!
