### ISSUE TITLE
Enable an audio device when switched to

### ISSUE THREAD

**Issue by sambul13** [xenolightning/AudioSwitcher_v1#2172]
Its a suggestion. If a disabled device hotkey is triggered in audio switcher, the soft should enable it and then switch to it. Useful for Mics, which are disabled by default, but may be enabled with a hotkey and switched to.

**Comment by xenolightning** [comment]
In what scenario is this happening?

Can you show Audio Switcher, along side control panel?

Can you switch to it using the control panel menu?

**Comment by sambul13** [comment]
For example, when one Mic (remote) is always On, but you want to switch to a different Mic (close-by) for a Recorder app, while its currently disabled. So you use one shortcut to a) enable target mic and b) make the launched app select it as a recording device. Some apps don't allow to choose a Mic, just use the default one, so without such shortcut you must relaunch the app after changing the default Mic, whether enabled or disabled.

This is not a bug, but simply a suggestion. AudioSwitcher can list disabled devices, and they can be assigned shortcuts to switch to. I suggest to automatically enable the disabled device, if the user switches to it by shortcut. Yes, one can enable the device in Windows Sounds before switching to it, but its an extra step.

**Comment by xenolightning** [comment]
Ahh I'm with ya now.

I have no idea what's involved in re-enabling a disabled device, so won't be on my radar to add this atm.

I may keep it in mind when adding features to some scripts, which could allow the device state to be changed.
