### ISSUE TITLE
how to know what audio output is being used when switching?

### ISSUE THREAD

**Issue by tataga** [xenolightning/AudioSwitcher_v1#2177]
this is very simple question so I will just put it briefly

say I have two sound devices registered in windows; realtek high definition audio and external usb audio dac so I could switch one with another for my taste. 

just clicking on music note icon(auto switcher tray icon) once will change my current device used so its very convenient.

but the issue here is, how do I know what specific device is currently being used since switching the device dosen't make any difference in the volume icon /switcher icon in the traybar so I need to hover over the icon to detect which device is on by now.

I combed through the settings to and fro  hoping to find the solution to no avail.

any ideas?

I am using windows 10 64bit with latest version of audioswitcher 1.8.0.142

thank you

**Comment by xenolightning** [comment]
You can use the "Show default device icon in tray" setting, which replaces the music note icon with the current active default device.

**Comment by tataga** [comment]
yes I already checked that option to see if it makes any difference, but since the two devices have same icon so I can't identify what is what. is there any way you can change the icon of the sound device/driver?

**Comment by xenolightning** [comment]
You can change it in the Control Panel menu, and in the device properties.

**Comment by tataga** [comment]
oh man 👍     didn't even think about that being in the properties. All set. Thank you , is the new 2.0 edition about to launch some time soon? just this small guy gets the job done very good.
