### ISSUE TITLE
Win10 april update 1803 doesn't seem to support

### ISSUE THREAD

**Issue by tomihbk** [xenolightning/AudioSwitcher_v1#2178]
Hello

It looks like the software has gone nuts after windows April update that is 1803. When i open the program, my playback list gets refreshed infinite times. Here is a gif of what i mean : https://media.giphy.com/media/SLpsPSAmnlimFeBc0m/giphy.gif

- [1.6.4.0]  Audio Switcher version
- [ Win10 Version 1803 ]operating system, and version

**Comment by xenolightning** [comment]
Try updating to the most recent version.

Confirmed the latest version seems to work fine on 1803
