### ISSUE TITLE
Enhancement - Custom Device Icons

### ISSUE THREAD

**Issue by kevinmarchant** [xenolightning/AudioSwitcher_v1#2182]
Currently using 1.8.0.142 (latest) on Windows 10 x64 1709 fully patched

Excellent program - really really useful.

A trivial cosmetic enhancement suggestion.

The default device manager icon for my Steelseries Wireless H headset is for "speakers" - it's a USB audio device.  I've looked into changing it using the Microsoft Device Metadata wizard but looks more hassle than it's worth.  It would be really useful to be able to specify a custom icon so that appears on the taskbar when active, and also to see icons in the pop-up menu.

Thanks for a really useful utility.

**Comment by xenolightning** [comment]
You can update the icon using the old "Sounds" control panel menu.

Can click the open control panel, from inside audioswitcher, and then right click the device and change icon.

![image](https://user-images.githubusercontent.com/6000196/44760613-c2b53d80-ab93-11e8-968e-7fb486a2ddca.png)

Can change to any standard icon, or a custom .ico file. Audio Switcher will reflect the icon chosen there in the application.

**Comment by xenolightning** [comment]
Regarding having images in the right click menu, it's something I will investigate, it might make the menu way to cluttered.

**Comment by kevinmarchant** [comment]
Oh my goodness.  For how many years have I not spotted that button !!!!!  (Time to break out the museum of old Windows OS’s :-) )

I’d just finished generating a resource DLL and changing the relevant reg entry - doh !

Thanks for your patience !

**Comment by xenolightning** [comment]
Haha, that other option sounds horrendous. 

Glad you have a better solution now :P

**Comment by Falen13** [comment]
Hi, and how to get to display different icons on the tray?
