### ISSUE TITLE
Audio Switcher 1.8 - favorite device forgotten?

### ISSUE THREAD

**Issue by phaolo2** [xenolightning/AudioSwitcher_v1#2183]
Audio Switcher: 1.8.0.142
OS: Windows7 Pro x64
Audio devices: Yamaha RX-V483 AVR connected via HDMI, Headphones
Audio drivers: Realtek HD Audio 6.0.1.7899 

I've noticed that sometimes Audio Switcher seems to "forget" its favorite setting for the AVR.
So, when I turn it on, AS doesn't allow quick switch (just stays on the headphones).
And when I check the program settings, the AVR device lost its star marking and I have to re-add it.

Do you know what could be the cause?
Can you try to fix this, please?

**Comment by xenolightning** [comment]
Thanks.

It's a limitation in Windows that's causing the device to be treated as a "new" device every time it's connected.

I use an internal identifier for the device to determine which devices are/aren't favourites, and reconnecting some devices causes them to get a new id, and the favourite device lost.

Sadly there's no way to change this default behaviour.

In the latest version, I enabled quick switching between all active devices when there are no favourites set.

The work around is to disable un-used devices, and you can quick switch on all other non favourite devices.
