### ISSUE TITLE
Use in another piece of software

### ISSUE THREAD

**Issue by MorGuux** [xenolightning/AudioSwitcher_v1#2185]
Hi, I've recently discovered this software, and it's exactly what I need,

I've been developing a program called Sim Racing Launcher, which allows sim racers to launch racing titles, along with other necessary software in one click. One great feature I would like to add to my software is the ability to set a certain audio device as default on game launch, and back to another on game exit.

I have already got the appropriate events for game launch/close, and I was wondering if I could use your software to manage the audio switching, if I pass it calls from my software.

Since you've kindly distributed the source code, do I have permission to bundle this software with mine, and use it.

I can either host the windows form inside my WPF app, add a button to run the audio switcher software externally, or have the audio switcher silent, with the user controls being in my software. Even command line arguments could be a method.

Please could you recommend any hints and tips for the best practice,

Cheers,
Morgan

**Comment by xenolightning** [comment]
I pulled out the switching functionality a packaged it into a nuget package a while back.

Repository: https://github.com/xenolightning/AudioSwitcher
Package: https://www.nuget.org/packages/AudioSwitcher.AudioApi.CoreAudio/4.0.0-alpha5

Feel free to use that, to do all the switching you need.

**Comment by MorGuux** [comment]
Ahh, thank you very much :D

Cheers,
Morgan
