### ISSUE TITLE
Audioswitcher "forgets" devices? (re-adding not possible, says "duplicate hotkey")

### ISSUE THREAD

**Issue by Ashra1** [xenolightning/AudioSwitcher_v1#2188]
System: Windows 10
Audio Switcher: 1.8.0.142

Hi,
AS worked perfectly for years until today. Thanks for this nice little tool! :)
One entry of my devices (USB Audio Device) just disappeared and if I try to add it again it says "duplicate hotkey". But it's not in the list. Is there any way to clear the whole database/reset the tool?

If I manually delete my second device and try to re-add it, the same problem occurs.

thanks for any input

**Comment by ghost** [comment]
I ran into this problem a while ago, and in the newest version, the bug seems to be fixed for me. It happened to me when I unplugged the USB device. @Ashra1, "Clear All" at least allowed me to re-add.

**Comment by sasjafor** [comment]
I am also experiencing this problem every time windows "forgets" (disconnect, driver change) a device and then the hotkey disappears. The desired functionality would probably be to just keep the hotkey and mark it as invalid/disabled. So that you can delete just that hotkey and redo it. Without having to clear all hotkeys.

**Comment by ghost** [comment]
That would be a good solution. The problem came back for me, and it's one of those inconveniences that makes me stop using the software. It's easier to click on the volume icon in the tray and switch there.

**Comment by ghost** [comment]
This is one of those times when design and user expectation is divergent. It's actually a feature in the application.

  
            var filterInvalid = !Program.Settings.ShowUnknownDevicesInHotkeyList;
            IEnumerable<HotKey> hotkeyList = _hotkeys;

            if (filterInvalid)
                hotkeyList = hotkeyList.Where(x => x.Device != null);

It's an option in the settings to show unknown devices. This issue should be closed.

**Comment by xenolightning** [comment]
Thanks @nilssohn.

Yeah, there is a setting to display hotkeys wit "unknown" devices attached, and they can be updated to the correct device using the edit function.

Also, the "clear all" function exists if the above doesn't work

**Comment by Ashra1** [comment]
Thank you!! :) Clear all worked just fine.

**Comment by g8up** [comment]
System: Windows 7
Audio Switcher: 1.8.0.142
I came across the same issue. 
I check the local setting `C:\Users\<XXX>\AppData\Local\AudioSwitcher\AudioSwitcher.json`.
I backup the setting, and then `clear all`, and then readd them .
I find that the devie-id (or guid) is changed. It may not be recgnized as a device.
And the programe may show the outdated device, which allow user to select and delete without `clear all` existing hotkey setting.
Thank for your program, and I like it!

**Comment by g8up** [comment]
as @xenolightning said, there is an option `Show unknown devices in Hotkey list` in `Settings` tab. If this option moved to `Hotkeys` tab, it will be better.
