### ISSUE TITLE
Right-click doesn't show my speakers, but they show up in playback devices.

### ISSUE THREAD

**Issue by molnizzle** [xenolightning/AudioSwitcher_v1#2191]
As the title says, my right click menu only shows my headset. This also means I can't quick switch between devices by clicking the icon. However, if I double click and fully open the app, my speakers show up fine...

My speakers are connected to my monitor which is receiving the audio via DisplayPort from my GTX 1070 GPU. I have the latest version of AudioSwitcher with the latest Nvidia drivers.

This is what I see when I right-click:

![Screenshot (1)](https://user-images.githubusercontent.com/37030095/54137459-52f5fa00-43e3-11e9-890d-89de666d9a6f.png)

This is what I see when I double-click:

![Screenshot (2)](https://user-images.githubusercontent.com/37030095/54137480-5ee1bc00-43e3-11e9-8f86-d922bfda74cb.png)

Any idea about how I can make AudioSwitcher able to quick-switch? In this state, it's not much faster than just opening windows settings.

**Comment by xenolightning** [comment]
If you have any favourite devices marked, the menu will only show favourite devices. It's a way to filter out devices, and only have the ones you care about display in menus, or be used in quick switch.

Favourite the Nvidia HD Audio, and it will display in the right click menu
