### ISSUE TITLE
Dual Device Switch

### ISSUE THREAD

**Issue by sol090** [xenolightning/AudioSwitcher_v1#2192]
Nice work you got here, Sean,
I'm currently using Version 1.8.0.142 and I couldn't find where to send you tips for functions to add so here I am. I'd love the possibility to bind a single hotkey command to two devices. (Combinding speakers with table mic and headset with headset mic.)
and again, Great work!

**Comment by xenolightning** [comment]
This is already an open feature request for this in v2.

https://github.com/xenolightning/AudioSwitcher_v1/issues/1969
