### ISSUE TITLE
Program works great! 

### ISSUE THREAD

**Issue by YummyOnionUnion** [xenolightning/AudioSwitcher_v1#2199]
Current version: 1.8.0.142
Win10 1909
HDMI to amp // Front jack to headphones
Nvidia
Sorry but maybe it is..

Right now if you launch the exe it will open a duplicate task. It might be an efficient workaround if the program notices an instance is already running, it sends a command to cycle next favorite, then close.

Simple click on the icon works great, truly. Tight executable.

**Comment by xenolightning** [comment]
It did something similar to this originally - but in a multi-user environment it caused so many issues.

Easiest solution was to allow multiple running instances.

**Comment by YummyOnionUnion** [comment]
That ENTIRELY makes sense.
 Thank you for the response! I know that the query does somewhat fall under
the category of switching-command requests.
The limitations are that of our choice of peripherals. Not your program. It
does exactly what it's meant to. Perfectly. :}
