### ISSUE TITLE
Show new audio device on switch

### ISSUE THREAD

**Issue by onelivesleft** [xenolightning/AudioSwitcher_v1#2200]
Small feature request: it would be nice if there was a quick toast message displaying what the new audio device is when it is switched (for example, when clicking left mouse on tray icon, or when hitting hotkey).  Could even just be by making the tooltip appear.

Alternatively, a small letter or number could be added to the bottom right of the tray icon to indicate the current device, but I'd be happy with the above.

**Comment by arekkusudesu** [comment]
Was thinking about this. It could also be nice to have the tray icon change to the device selected. I switch from TV speakers to my headphones quite often and the only way to tell which device is in use is by hovering over the tray icon, which has a second delay.

**Comment by xenolightning** [comment]
If you enable the "Show Default Playback Device icon in tray" setting - it will display the icon of the current active device. You can change the Icon through the System Control panel - and it will be reflected in the tray.
