### ISSUE TITLE
Know program that switches balance/volume, etc?

### ISSUE THREAD

**Issue by m-7761** [xenolightning/AudioSwitcher_v1#2201]
I'm looking for a way to switch the devices settings, not devices. This is too minimal! Does anyone know an alternative?

EDITED: This (https://superuser.com/questions/693462/is-there-a-handy-alternative-to-change-volume-balance-in-windows-7) link suggests two programs called SimpleSndVol and Volume². I think Winaero is a reliable source. The other goes to a Cyrillic site that looks scary but it's the better of the two and is impressive to look at. It has hotkeys to control balance which is really what I wanted best case scenario.

http://winaero.com/download.php?view.12 (SimpleSndVol)

http://volumesqr.at.ua/publ/ (Volume²)

NOTE: Volume² might be a timed demo. It's in Cyrillic. But there is a key registration system in the app.

**Comment by xenolightning** [comment]
Go check out eartrumpet, it's more in depth.

https://github.com/File-New-Project/EarTrumpet
