### ISSUE TITLE
[Suggestion] Explore integration with RTX voice?

### ISSUE THREAD

**Issue by msanigar** [xenolightning/AudioSwitcher_v1#2206]
Version: 1.8.0.142
OS: Windows 10

Devices used: Creative SB-X sound card (USB) w/Sennheiser G4ME zero headset, Trust GXT 244 Buzz mic (USB), Logitech T10 speakers (Aux).

Suggestion:
Anyone using RTX Voice sets the audio device(s) using this application; it would be amazing if AS could integrate with that, so that we don't have to change devices in two applications.  Unsure if they have an API available or any hooks exposed but suspect popularity will grow over time.

Cheers!

**Comment by xenolightning** [comment]
I suspect they don't have an API for RTX Voice, it's super early beta.

The best we could hope for at this stage would be a registry setting or a file based setting, determining the active device used for RTX.

Are you looking to switch "default" devices, but retain the sound processing no matter which device was selected?

It seems like more of a feature in RTX Voice than Audio Switcher, and they'd have to support hotkeys.

What would be cool is if they release the sound processing library as an SDK - and you could integrate with it. At that point Audio Switcher could take over from RTX Voice.
