### ISSUE TITLE
[Question] Elgato stream deck/mini  support?

### ISSUE THREAD

**Issue by msanigar** [xenolightning/AudioSwitcher_v1#2207]
Version: 1.8.0.142
OS: Windows 10

Devices used: Creative SB-X sound card (USB) w/Sennheiser G4ME zero headset, Trust GXT 244 Buzz mic (USB), Logitech T10 speakers (Aux).

Question: Is there any way to use Elgato stream deck (mini) switches as hotkeys for AS?  I'd like to be able to hot-swap which mic input/audio output I'm using in the most seamless way possible, but don't want to pull the trigger til I know it'll work -- Elgato gear is expensive!

Cheers!

**Comment by xenolightning** [comment]
I'm not 100% sure how the Elgato StreamDeck works, but from what I know you can assign a switch on the keypad to a hotkey.

If you can do this - you'd be able to assign a key to a specific key combination and bind that hotkey combination in Audio Switcher.
