### ISSUE TITLE
feature suggestion: custom names on devices

### ISSUE THREAD

**Issue by se4203** [xenolightning/AudioSwitcher_v1#2208]
I'm on 1.8.0.142 in Win10. Here's my set-up:

- My "main" headset (with mic) in the 3.5 plug on the laptop.
- Speakers attached to the monitor's 3.5 plug (monitor attached via DP)
- Wireless headphones (no mic) in the 3.5 plug on the dock (great for listening in on meetings in the bathroom without the risk of leaving mute off)

All of these get quite cryptic labels in the GUI so it would be great if I could label them myself.
The speakers, for example, get the monitor's model number as their label.

Note: I don't want to mess with the actual labels (shown in the Control panel) - this would be a Audio Switcher-internal feature.

**Comment by se4203** [comment]
typo

**Comment by xenolightning** [comment]
You can set a device name using Windows, and the name is recognised in Audio Switcher.

To do this you can open the Legacy Sound Control Panel (using the control panel link in AS)
Right click a device and set the name - see screenshot

Outside of renaming them in Control Panel - there's no other way to reliably add names to devices.

![image](https://user-images.githubusercontent.com/6000196/84080800-e2e48280-aa30-11ea-83c2-0779f3061900.png)
