### ISSUE TITLE
MSE found Trojan:Win32/Wacatac.D!ml from a download from the github link

### ISSUE THREAD

**Issue by rosytoes** [xenolightning/AudioSwitcher_v1#2209]
AudioSwitcher_v1
Windows 7 Service Pack 1
Ryzen 5 1600

My friend has just downloaded the .exe from the github link from https://www.audioswit.ch/er. Microsoft Security Essentials immediately quarantined it as having Trojan:Win32/Wacatac.D!ml. Could you please confirm if this is a false positive or have you been compromised?

**Comment by rosytoes** [comment]
I downloaded using the same link on my Windows 7 machine and found no problems.

**Comment by xenolightning** [comment]
The github link - routes back to here and the release that has been current for a long time :)

It's likely a false positive from MSE - I'll attach a virus total scan from the github release links

https://www.virustotal.com/gui/url/54af106484a4c323d717f3211e3d3c0226ae33e3e12475f60a32f6066e3e9632/detection

https://www.virustotal.com/gui/url/b1b61dd0d42c9c87a7ad7673ab722506a64ca00d069486c514132eebf7bede70/detection
