### ISSUE TITLE
sdaudioswitch.exe system error

### ISSUE THREAD

**Issue by Eviscerata** [xenolightning/AudioSwitcher_v1#2210]
I keep getting an error message. The code execution cannot proceed because VCRUNTIME140_1.DLL
was not found. Reinstalling the program may fix this problem.

I have used audio switcher for months and never had this issue before. 

- [1.8.0.142 ] I have listed the Audio Switcher version
- [windows 10 latest ] I have listed my operating system, and version
- [I use a headset or speakers, a yeti mic or headset mic. Everything works but  I started getting a weird pop up ] Include any details about the audio devices on the system
- [ I dont think I am using either for sound] If you are using Nvidia or AMD for sound, include the driver versions
- [ not a switching issue] This is not an issue about setting more than one device as default from a hotkey, quick switch or other relating switching activity.

And do remember this application is developed and distributed **FOR FREE**, you should have no expectation that an issue will be fixed in a reasonable time-frame.

**Comment by xenolightning** [comment]
That seems a little weird.

The VCRUNTIME stuff has to do with other runtimes - not actually used by Audio Swticher.

Where are you downloading it from? Here on GitHub?

Maybe try installing the .net 4 runtime.

https://dotnet.microsoft.com/download/dotnet-framework/net40

**Comment by Eviscerata** [comment]
Thank you for the quick response. I tried downloading the .net 4 runtime but my system already has that version or newer. I don't think I got audio switcher from GitHub, but in the support section, it listed GitHub as a source for help. I keep getting the error message sdaudioswitch.exe so I figured it was related to my app. I now realize that I cant switch audio devices with my Streamdeck xl. With a button push, I could switch between headset or speakers but since this morning I lost that ability. And if I leave the error message alone it doesn't keep happening, but the second I close the error it keeps coming back.

**Comment by Eviscerata** [comment]
I believe I have fixed the issue now, redid all my hotkeys with audio switcher and stream deck and it seems to be fine now. Thank you again for your reply

**Comment by xenolightning** [comment]
No idea what `sdaudioswitch.exe` is - it's not this audio switcher for sure. 

You can ensure you are running the actual supported version by grabbing the latest release from this page: https://github.com/xenolightning/AudioSwitcher_v1/releases

I know people have been bundling malware and redistributing audio switcher - so it may be related.
