### ISSUE TITLE
Suggestion: Ability to disable devices in quick switch mode

### ISSUE THREAD

**Issue by iitaliics** [xenolightning/AudioSwitcher_v1#2211]
I have an output device on my PC which I use exclusively for a specific program, and two other devices which I use regularly that I cycle between using the quick switch mode. A quality of life feature I'm suggesting might be possible is the ability to take an output device out of the rotation for the quick switch, rather than having to always skip over the output device I'm not using. I know this can be achieved by disabling the device in the control panel, which makes it not show up at all in the program, however I still need the output to be enabled for my specific use-case. Is this idea feasible? 

Thanks.

**Comment by xenolightning** [comment]
If you favourite the two devices you want to switch between the quick switch feature will only switch between those two devices.

It creates the "rotation" from all devices, unless you favourite devices - then it creates the rotation from all favourited devices
