### ISSUE TITLE
"Duplicate hotkey detected"

### ISSUE THREAD

**Issue by i-make-robots** [xenolightning/AudioSwitcher_v1#2212]
v1.8.0.142
Windows 10 build 19041.450
Windows Natural ergonomic keyboard 4000

Fresh installation.  Open Audio Switch > preferences > hotkeys
Add key, output device 1, BroswerBack button.
Add key, output device 2, BrowserForward button.  

Seen: "Duplicate hotkey detected."
Expected: New hokey added.

Maybe also helpful to show which key is duplicate.  "duplicate of CRTL+SHIFT+A" or something.

Thank you!

**Comment by xenolightning** [comment]
If you enable the setting to show hotkeys for unknown devices - you can see any devices that no longer exist, and if any hotkeys are associated with them.

Alternatively if there is nothing there - another program might have that hotkey registered.
