### ISSUE TITLE
Disabled devices still available to choose from

### ISSUE THREAD

**Issue by sonicblis** [xenolightning/AudioSwitcher_v1#2214]
Please ensure you include/confirm the following information before submitting an issue.

1.8.0.142
- [x] I have listed the Audio Switcher version

Windows 10, version 1909 (OS Build 18363.1198)
- [x] I have listed my operating system, and version

![image](https://user-images.githubusercontent.com/5229682/99822349-1a4b7500-2b21-11eb-91ec-fc73f7f5aa24.png)
- [x] Include any details about the audio devices on the system

N/A
- [x] If you are using Nvidia or AMD for sound, include the driver versions
- [x] This is not an issue about setting more than one device as default from a hotkey, quick switch or other relating switching activity.

And do remember this application is developed and distributed **FOR FREE**, you should have no expectation that an issue will be fixed in a reasonable time-frame.

I have disabled audio devices that I don't want as options to switch to, but they still show up in the list despite not having "Show Disabled Devices" selected.

**Comment by xenolightning** [comment]
As a work around - you can mark them as favourite and only favourite devices will be displayed in the context menu

**Comment by sonicblis** [comment]
Perfect, thanks. CJ From: Sean ChapmanSent: Sunday, November 29, 2020 2:10 PMTo: xenolightning/AudioSwitcher_v1Cc: CJ; AuthorSubject: Re: [xenolightning/AudioSwitcher_v1] Disabled devices still available to choose from (#2214) As a work around - you can mark them as favourite and only favourite devices will be displayed in the context menu—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
