### ISSUE TITLE
Trojan.Malware.300983.susgen detected in .exe file

### ISSUE THREAD

**Issue by NyteMyre** [xenolightning/AudioSwitcher_v1#2220]
My virusscanner suddenly quarantined Audioswitcher for **IDP.generic**. I uploaded the file to virustotal for a scan and it detected "**Trojan.Malware.300983.susgen**"

I redownloaded the latest .exe file from Github and reuploaded with same results

Scan details:  
https://www.virustotal.com/gui/file/38017bffa6be6782fc009fd548d888a8910c447cad328a2e95b1e80009308dc4/detection

**Comment by xenolightning** [comment]
Gah - thanks for reporting that.

It's definitely a false positive - no idea what would be flagging it as malware. I assume it's probably the exe packing - but really weird.

I've submitted a false positive - but the current exe hasn't changed or been re-uploaded since 2018

**Comment by xenolightning** [comment]
Got confirmation from SecureAge APEX that it was a false positive.

**Comment by NyteMyre** [comment]
I am using Avast btw, who first quarantined the .exe file

**Comment by xenolightning** [comment]
Avast had a problem with it a long while back - and I submitted a false positive there too. Hopefully should be sorted now 😬
