### ISSUE TITLE
Hotkey already in use

### ISSUE THREAD

**Issue by tuxydoh** [xenolightning/AudioSwitcher_v1#2224]
Even after resetting hotkeys, both manually in json file and via the clear all tool, when attempting to set the switch, app gives error that hotkey is already in use.  Keys attempted are f16-f19 via a mini keyboard. 
Version 1.8.0.142
Win10 19043 build

**Comment by xenolightning** [comment]
That's odd.

It uses a global hotkey, which can be shared with other applications. So if you have another application with the same hotkeys registered AudioSwitcher may not be able to register them.

I will give the extra f keys a look, I wouldn't have thought "virtual" key codes would have been an issue though

**Comment by tuxydoh** [comment]
A complete reinst2seemes to have fixed it. Not sure what happened

~Patrick
________________________________
