### ISSUE TITLE
Icon/status balloon wont update even though device switches

### ISSUE THREAD

**Issue by fluxnz** [xenolightning/AudioSwitcher_v1#520]
(fellow Kiwi) 
build: 1.6.3.1
Win 8.1 64 bit - when i select my device via right clicking the taskbar icon, the playback device changes however the status balloon and icon remain the original device.
See img:
![audioswitcher](https://cloud.githubusercontent.com/assets/10953686/6142750/7b1695ec-b221-11e4-93ff-147b434b870d.png)

This occurs after each reboot, but once i open the interface itself from the tray and minimize/close the status balloon and icon then update. Seems to only work once I open and close the GUI. 

On another note, the quick switch mode seems to do nothing in this build - previous builds it would switch devices, now it does nothing :) - no errors, just nothing occurs even though the tick box is selected.

Also,

**Comment by xenolightning** [comment]
Can reproduce this. Looks as though the Window needs to be shown before some functionality works properly.

I'll investigate it a bit further.

Quick switch seems to work fine for me. It suffers from the same issue if the main window isn't opened first.

**Comment by fluxnz** [comment]
Thanks. I removed the favourite device line however find the same, even after displaying the GUI first.
The click on the icon is registered as i see it highlight when i click but no device change.
Config file confirms the quick switch option is displayed too.
Maybe its my PC heh
![untitled](https://cloud.githubusercontent.com/assets/10953686/6152796/edd985c2-b284-11e4-9677-624f7a346ed3.png)

Ill slip in a feature request: a hot key option to perform quick switch rather than pick a single key per individual device. So the same function as clicking the icon (which granted doesn't work for me heh)

**Comment by xenolightning** [comment]
Hah, the hotkey quick switch is coming in Version 2.

Can you post your config file in this issue? I'll see if anything is up with it.

**Comment by fluxnz** [comment]
{
  "AutoStartWithWindows": "True",
  "CheckForUpdatesOnStartup": "False",
  "CloseToTray": "True",
  "DisableHotKeys": "True",
  "DualSwitchMode": "False",
  "EnableQuickSwitch": "True",
  "HotKeys": "",
  "PollForUpdates": "0",
  "ShowDisabledDevices": "False",
  "ShowDisconnectedDevices": "False",
  "StartMinimized": "True",
  "StartupPlaybackDeviceID": "b62693c2-f59f-439f-aa01-113e38d1584a",
  "StartupRecordingDeviceID": "ce5e129a-07ff-47b2-acbd-bd18eab6d625",
  "WindowHeight": "420",
  "WindowWidth": "300",
  "ShowDPDeviceIconInTray": "True",
  "FavouriteDevices": "[]"
}

**Comment by xenolightning** [comment]
Quick Switch uses the Favourite devices to switch between.

If you set your two playback devices as favourites, then quick switch should work for you.

v2, it's a unicorn! It does work but there's a few things that need sorting before it sees the light of day.

**Comment by fluxnz** [comment]
Well - so it does... i swear it didn't require the favourites being defined in previous versions... either way - that functions if they are defined as favourites. 

Thanks :+1:

**Comment by xenolightning** [comment]
Sweet.

I'll keep this issue open until the refresh of the menu items is fixed. Will be included in 1.6.3.2, which may go out tonight/tomorrow.
