### ISSUE TITLE
Add support for switching when application starts

### ISSUE THREAD

**Issue by tmiland** [xenolightning/AudioSwitcher_v1#536]
Hi,

as the title says, it would be nice for support for switching when an application starts.

Let's say i start game.exe, then AudioSwitcher switches to the headset automatically. :)

And Maybe with a delay to switch back, in case of random shutdowns of the set app. :)

Regards.

**Comment by xenolightning** [comment]
Hi,

This is already a planned (and completed) feature in Version 2.0.

The switch back on application on closing is unlikely to happen in the release, it's really specific and could cause odd/annoying behaviour.

-Sean
