### ISSUE TITLE
Feature request - Playback + Recording change at the same time

### ISSUE THREAD

**Issue by nhowland** [xenolightning/AudioSwitcher_v1#567]
Thanks for this very handy little utility. 

One thing I'd like to see added is some type of convention to change the playback and recording devices at the same time. Either through a hotkey or favorite selection.

Use case is that I've got two different device "profiles" (playback device + recording device) that I'd like to quickly switch between. I can almost get there now, it takes a couple clicks to do it, but it would be great if a combination could be created to change both at the same time.

**Comment by xenolightning** [comment]
This is already planned for the Major 2.0 release. 

It includes a scripting engine (JavaScript) in which you can write your own "profiles" and switch between them.

I originally thought of doing profiles as you suggested, but fleshed it out into scripts. This allows you to not only change more than one device at the same time, but you can also reset the volume levels of the devices, etc...

It's kind of a "Rolls Royce" solution, so everyone can do exactly what they want.

These scripts will be able to be "started" by macro events, which include an application starting, hotkeys, and even (ctrl/shift/alt) clicking on the icon in the tray. 

This has already been built as in in 2.0, so will close this issue.

Cheers.
