### ISSUE TITLE
Crashes and not responding and some tips to improve

### ISSUE THREAD

**Issue by furyanaor** [xenolightning/AudioSwitcher_v1#586]
Hey, great application!
I came across a number of crashes and errors when audio device is connected in real time when the application runs in the background.
I'm talking mainly about the Bluetooth device, it connects when I run it, and then the application crashes and I need to turn it back on.

I think we should find a repair Iiail if not, then at least be placed on HOLD in STARTUP Bluetooth device connects to the application before rising.
(I personally programmed STARTUP 'late' for this application just because of this problem, but of course in the application of this knowledge to fend for himself).

Tips to improve:
Bluetooth matter, when a new device connects identified would like the application will go through Bluetooth audio automatically (I've seen an application that knows to do it, but it has a different fault so I kept searching and found it, and it's great just a few small improvements!).

'Single HOTKEY, choosing between, favorite devices. (I have no need in HOTKEY for each device and device. Enough to have one that I would use to choose between all of them)
By the way, 'quick transition' is not working properly ... time's well and time's, depending on the mood.

Visually I think we should put the standard icons of Windus unusual to not see eye there taskbar next to the clock.
I'm a graphic designer and I can design your logos if you want =]

And there is no need and taste preferred device will display the full name of the device, these are just the 'nickname', it is possible to change the characteristics of the sound.

Thank you! @

**Comment by xenolightning** [comment]
There's a few points in this.

The first is a new device connected when the application is running. I'll raise a bug for this, probably won't be in the next version, but the one following.


Change sound device when plugged in - This is something that is better suited to v2.0, I will raise a feature request and assign it to v2.

Single hotkey to change multiple device - already in v2.

v2 also has new icons, and will allow the user to create & use their own icons and themes.

Nicknames can be done through Windows. I don't plan on implementing a renaming feature any time soon.

**Comment by xenolightning** [comment]
#591 
https://github.com/xenolightning/AudioSwitcher/issues/7

**Comment by furyanaor** [comment]
Thanks for the quick and detailed response!
On which version V2 are you talking about?
I have not seen anything like this and the automatic update does not warn about it.

In addition, I think you mistake my meaning regarding the 'nickname':
Through the WINDOWS possible to change the names
But the software does not show - just - the name was conducted,
These all full name of the device.
I do not need to see the whole name (by the way can not be changed in any way),
These I would like to see - just - this section as editable via the Windows on the device name.

Thanks again !

**Comment by xenolightning** [comment]
Version 2, is in development, and hasn't been released yet. It has a large feature set, you can see a preview by going to http://audioswit.ch/er and scrolling to the Version 2 section.

I think I know what you mean by the nicknames. The part you can change through Windows should be shown in the application, and included in the full name of the device.

The reason for displaying the full name is because people may have multiple "Speakers"/"Headphones", in which case showing the full name is actually useful to distinguish them from each other. It's unlikely that this will change.

**Comment by furyanaor** [comment]
You hit the matter my friend.
I will wait patiently,
and I ask to consider adding the settings menu option to hide the unwanted part where ...
Thanks again!

**Comment by xenolightning** [comment]
1.6.4.0 is an attempted fix for the crash you are experiencing when connecting your bluetooth device.

**Comment by furyanaor** [comment]
Fine, Thanks !
still waiting for V2 for singl HOTKEY and icon's

2015-03-02 1:40 GMT+02:00 Sean Chapman <notifications@github.com>:
