### ISSUE TITLE
Hot key bug when updating sound driver

### ISSUE THREAD

**Issue by OVERKILL27** [xenolightning/AudioSwitcher_v1#592]
I updated my realtek driver and as a result all of the sound devices that where using that driver and had a hot key for them had their hot key removed. Now when I try to re add those hot keys Audio Switcher tells me that there is a "Duplicate Hot Key Detected" and that stops me from binding them back with the same hot key I had before the driver update.

**Comment by xenolightning** [comment]
Give your system a reboot. It should free up the old hotkeys and allow you to re-register them

**Comment by OVERKILL27** [comment]
Thanks for the quick reply but unfortunately that did not help :(

**Comment by xenolightning** [comment]
Try deleting the line starting with Hotkey in the json config file.

You can delete the whole file if you want, but it will reset all of your settings.

**Comment by OVERKILL27** [comment]
Yup, that did it, thanks for the help! Great application by the way, looking forward to v2.0.

**Comment by xenolightning** [comment]
Sweet.

We all are! lol

Closing as resolved :)
