### ISSUE TITLE
Custom device icons

### ISSUE THREAD

**Issue by heavyLobster2** [xenolightning/AudioSwitcher_v1#609]
Allowing custom device icons would be neat. The Windows audio device dialog lets you pick custom icons, which is helpful when the default icon doesn't match your device. The newest AudioSwitcher update made it detect my TV as some kind of receiver, so now it has the receiver icon instead of the TV one, and I can't change it in AudioSwitcher.

Custom icons directly in AudioSwitcher, or using the ones you set in the Windows dialog, would be awesome. Allowing .ico icons for non-pixely resizing would be cool too.

Thanks! AudioSwitcher is great and I use it on a daily basis. :)

**Comment by xenolightning** [comment]
Audio Switcher slowly moving away from the "default" custom icon behavior. it caused way too many issues.

There won't be a way to change the icon in Windows, and have that appear in Audio Switcher, from this point on.

I may introduce the ability to add custom icon via the Audio Switcher interface. But that also won't be happening anytime soon. 

Finishing 2.0 is my priority over introducing new features.
