### ISSUE TITLE
Dont start on boot

### ISSUE THREAD

**Issue by jhaveDK** [xenolightning/AudioSwitcher_v1#610]
I have checked to "start with windows" but its dont start. 

Location: C:\Program Files (x86)\Audioswitcher
OS: Windows 8.1 pro 64bit

**Comment by xenolightning** [comment]
Does the option stay checked?

Have you tried running as Administrator?

It's most likely a permissions issue.

**Comment by jhaveDK** [comment]
Yes its checked and i have changed it so its run with admin rights

**Comment by xenolightning** [comment]
Let me know how you get on. Running with Admin will absolve Audio Switcher as the root cause.

Potentially Anti-Virus/Anti-Malware Applications can interfere with programs requesting startup permissions.

**Comment by jhaveDK** [comment]
Hi, 
its run as Administrator: http://gyazo.com/f8ce3d4241c0fe7a88a36175486d0646 
My settings: http://gyazo.com/d78cd53bba2533147f674e82d2dae716

And the file location is: C:\Program Files (x86)\Audioswitcher
