### ISSUE TITLE
AS   V. 1 6 4 0  installs on every start of windows

### ISSUE THREAD

**Issue by RockySpears** [xenolightning/AudioSwitcher_v1#654]
win 8.1 64bit

Switcher works fine but asks for (and seems to need) installation every time windows starts.

Any ideas why?

Rocky

**Comment by xenolightning** [comment]
The exe doesn't actually install anything. It's considered a "portable".

Can you screenshot the message you are getting?

**Comment by RockySpears** [comment]
I get this, every time I start my computer, switcher will not work unless I
go through the install, it will however remember the Hot keys I set for
this previously

[image: Inline images 1]

Pete

**Comment by xenolightning** [comment]
Can you post the image on GitHub, the emails don't attach images properly.

Cheers.

**Comment by RockySpears** [comment]
![audio sw 1 6 4 0](https://cloud.githubusercontent.com/assets/11507393/6692469/ae9b8bd0-ccc4-11e4-9278-968d723586c3.jpg)

**Comment by xenolightning** [comment]
Thanks.

That message appears as a security warning, as is built into Windows.

I notice you are running it out of a temp folder. Try extracting AudioSwitcher.exe into another folder. Program Files/Documents/Desktop, and running it from there.
