### ISSUE TITLE
Hot-key issue

### ISSUE THREAD

**Issue by mgyellow** [xenolightning/AudioSwitcher_v1#657]
Hi,

Almost started writing my own audio switcher, until I ran into yours :+1: 
The issue:

I just updated my audio drivers (Realtek), rebooted my pc and now my hotkeys are "gone".
The quotes are there because, although the hotkeys don't work anymore *and* they don't appear in your app under the hotkeys tab, I can not add a new hot key for the same key I used before. Your app shows a red exclamation mark, which says the keycombo is already detected.
I can create a new hotkey with a different keycombo.

How do I get the same key-combo's working again?

Thanks, great work xenolightning.

Update:
I edited the AudioSwitcher.json file and cleared the HotKeys item, so AudioSwitcher doesn't register the hotkey on startup. That fixed my initial issue.
Leaves the problem for the unmatched hotkeys not showing in the hotkey list though.
Also, having to recreate the hotkeys with every driver update seems tedious.

**Comment by xenolightning** [comment]
Good ol' driver update.

Windows is ridiculous in the way it treats driver updates, it creates new device entries every time. There's no way around this.

The best way to clear them is, close AudioSwitcher, delete the json file, reboot pc, open AudioSwticher, re-check settings + add hotkeys.

The hotkeys are system side, so they get registered and the driver update invalidates the hotkeys, and they can't be removed.

Looking to make this a little nicer in v2.
