### ISSUE TITLE
Audio Switcher 1.6.4.0 not working on Windows 8

### ISSUE THREAD

**Issue by mpenguin** [xenolightning/AudioSwitcher_v1#660]
Just installed Audio Switcher 1.6.4.0 (placing the file and running the .exe as administrator to adjust settings).

It's running in my tray, and I can change my output device, but it doesn't actually switch anything. I need to select a new output device and restart my computer for changes to take effect.

I have confirmed that I have .NET 4.0 installed.

**Comment by xenolightning** [comment]
Does it switch when you use control panel?

**Comment by mpenguin** [comment]
Not sure what you mean.

If I am using my speakers and watching Youtube, the audio won't switch to my headphones when I switch it with Audio Switcher. I have to switch to headphones, then either jump ahead/back in the video or reload the video for the switch to happen.

**Comment by xenolightning** [comment]
Ahhh ok, see if it works for other applications (not YouTube). Flash sometimes doesn't like switching audio whilst playing.

**Comment by mpenguin** [comment]
Cool. It does work when watching videos on my HDD, so it appears to be a flash problem.

Thanks for the help and fast response!

**Comment by xenolightning** [comment]
NP.
