### ISSUE TITLE
Settings not setting 

### ISSUE THREAD

**Issue by Lnau** [xenolightning/AudioSwitcher_v1#711]
AudioSwitcher settings disappearing every few days.... ie:  the "open to tray" gets unchecked and needs to be re-checked. 

AudioSwitcher is a very slick and nice app... well done!
Thanks!

**Comment by xenolightning** [comment]
The application will reset the settings if it cannot find/access the settings file, or the settings file is corrupt.

**Comment by Lnau** [comment]
Thanks for the reply

It's a random thing ...I have AudioSwitcher set to load when Windows start
but the issue still occurs 2 or 3 times a month.

Thanks
Larry
