### ISSUE TITLE
Old device shortcuts cannot be deleted

### ISSUE THREAD

**Issue by CntZer0** [xenolightning/AudioSwitcher_v1#829]
If you assign a shortcut to a device and then reinstall it, it will not appear on the list and you wouldn't be able to assign the same shortcut again. I resolved this by recreating the json, but something inbuilt would be nice.

**Comment by xenolightning** [comment]
Yep, sounds like something that could happen.

I'll look at fixing this one for the next release.

In the meantime, the json file is just a text file, and you can just delete the line "Hotkeys", will save you from reconfiguring the whole app.

Actually thinking about it, a quick solution would be a button to clear all hotkeys.
