### ISSUE TITLE
No crash, no error but switching won't work on Windows 10

### ISSUE THREAD

**Issue by neFAST** [xenolightning/AudioSwitcher_v1#850]
I don't know if you will have time to look at a bug that appears on a beta OS.
However if you can provide a debug version with more trace, I would like to understand why it doesn't work!

EDIT: this may help:
https://github.com/davkean/audio-switcher/issues/32

**Comment by xenolightning** [comment]
Looks like you've found the answer!

I'll open a bug in the Audio Api project to track this, all the actual interfacing code is in that repo.

**Comment by xenolightning** [comment]
** Will leave open to officially close in the 1.6.5.0 release.

**Comment by neFAST** [comment]
Nice, any ETA for the fix ?

**Comment by xenolightning** [comment]
Requires an api release for this.

I also have no way of testing it, as I'm not using the Technical Preview on any of my devices.

**Comment by neFAST** [comment]
I'll be happy to test it for you :)

**Comment by xenolightning** [comment]
Cheers. It should be a quick fix, so I may release the test version in the next few hours. Will post a link to it in here.

**Comment by neFAST** [comment]
Cool, but I'm on UTC+1 so I'll test it tomorrow morning :+1:

**Comment by xenolightning** [comment]
UTC+12 here, so couldn't be further away. 

Looks like I've fixed it, I'll drop a test build later this afternoon.

I have a feeling it will change again

**Comment by xenolightning** [comment]
Win10 RC build:

https://github.com/xenolightning/AudioSwitcher_v1/releases/tag/1.6.5.0-rc1

**Comment by neFAST** [comment]
Unfortunately it behaves the same. No crash but the default devices stays the same

**Comment by xenolightning** [comment]
https://github.com/xenolightning/AudioSwitcher_v1/releases/tag/1.6.5.0-rc2

Give that a go.

If it doesn't work, I'll download the Windows 10 TP, and give it a look over the weekend.

**Comment by neFAST** [comment]
Nope :(

**Comment by xenolightning** [comment]
What build of Windows 10 are you using? 

I know that Audio Switcher did work for a period of time on Windows 10, so the change must've been relatively recent.

**Comment by neFAST** [comment]
10061

**Comment by xenolightning** [comment]
Tested rc2 and working on 9926. Am updating to latest on the fast strain, and will test again.

**Comment by neFAST** [comment]
When I discovered your AudioSwitcher I was already on 10041 so I can't tell if it was working before.

**Comment by xenolightning** [comment]
Can confirm it doesn't work on 10061

**Comment by xenolightning** [comment]
Build number still hasn't been updated to something useful in Win10.

Win10 = 6.2.9200.0

Will drop in the selective changes and put out another rc

**Comment by xenolightning** [comment]
Grab RC3. It should be working now.

https://github.com/xenolightning/AudioSwitcher_v1/releases/tag/1.6.5.0-rc3

**Comment by neFAST** [comment]
Works fine!

**Comment by xenolightning** [comment]
Great. 

Win10 TP will be officially supported form 1.6.5.0 onwards.
