### ISSUE TITLE
Audio device not detected when unplugging and plugging in again

### ISSUE THREAD

**Issue by BAPostma** [xenolightning/AudioSwitcher_v1#868]
On my laptop I have a setup consisting of builtin speakers and an audio output via my external HDMI monitor. When I unplug the monitor whilst that device is selected for audio playback the device properly returns to the built-in mode and switches the icon (a setting I've enabled).
After plugging the HDMI cable back in, the application doesn't detect the new device. Also swapping output device using Windows' control panel (Win 8.1) doesn't bring the icon of the HDMI device back.

**Comment by xenolightning** [comment]
Hmm, this seems like a very specific scenario when using Audio over HDMI.

It's very strange that the application isn't picking up the new device.

I'm assuming, because you were able to switch it via Control Panel, that the device is showing up in Windows?

I may be able to recreate this, using my audio setup. 

Does the laptop have a graphics card? NVidia/AMD? Or is in using onboard Intel/AMD?

**Comment by BAPostma** [comment]
Hey Xeno,

- Yes, I can switch via the control panel as it shows up there. I.e. Windows detecting it is all functioning normally.
- No, is is an Asus UX31A which has an onboard Intel HD Graphics 4000 chip

**Comment by xenolightning** [comment]
Thanks.

I'll investigate it and provisionally mark it for release in the next release 1.6.5.1

**Comment by xenolightning** [comment]
Confirmed that there is a scenario where devices are "Invalid" when added to the system.

Devices are considered 'added', when they are plugged in. This could occur for almost any removable audio device.

Issue added to Api project to track the fix.

https://github.com/xenolightning/AudioSwitcher/issues/15

**Comment by vertigo220** [comment]
I just experienced this with a Bluetooth device. Whenever connecting a device, it shows up in Windows' playback devices window, but AudioSwitcher has to be closed out and restarted for it to show up.

**Comment by CntZer0** [comment]
This seems like the issue I was having and already reported over [here](https://github.com/xenolightning/AudioSwitcher/issues/10)

I often change my presentation mode (from extended to monitor only) which basically unplugs the TV as an audio device. Once it's enabled, right clicking the audioswitcher bugs out the menu (flickers in and out for a minute), and the TV is sometimes seen as a device sometimes not.

**Comment by xenolightning** [comment]
@CntZer0 Yeah, it's definitely a known issue in 1.6.5.0, there's about 4 issues related to it atm.

Have another issue in the Audio Api to fix, there should be a client release today or tomorrow.
