### ISSUE TITLE
Issues with laptop docks

### ISSUE THREAD

**Issue by liujunhui74** [xenolightning/AudioSwitcher_v1#950]
I have an HP laptop with a dock. The Plantronics C320M USB headphone is plugged into the dock. Sometimes when I put back the laptop onto the dock, there is no option to switch to the C320M headphone in AudioSwitcher. However, restarting AudioSwitcher gets back everything.
If an easy fix is not possible, adding a "refresh" option in the menu will be just as good. Please think about it.

**Comment by xenolightning** [comment]
This could be related to (if not the same as) #868 

I'm still trying to reliably replicate the issue.

It may be caused by the device being in an "invalid" state when first connected, so it gets ignored.
